CREATE SEQUENCE datafile_id_seq START WITH 5000 NOCACHE;
CREATE SEQUENCE dataset_id_seq START WITH 5000 NOCACHE;
CREATE SEQUENCE icat_authorisation_id_seq START WITH 5000 NOCACHE;
CREATE SEQUENCE investigation_id_seq START WITH 5000 NOCACHE;
CREATE SEQUENCE publication_id_seq START WITH 5000 NOCACHE;
CREATE SEQUENCE sample_id_seq START WITH 5000 NOCACHE;
CREATE SEQUENCE software_version_id_seq START WITH 5000 NOCACHE;
CREATE SEQUENCE study_id_seq START WITH 5000 NOCACHE;
CREATE SEQUENCE topic_id_seq START WITH 5000 NOCACHE;

