CREATE TABLE DP_CONSTANTS
(
ID NUMBER NOT NULL,
NAME VARCHAR2(30) NOT NULL,
VALUE VARCHAR2(4000) NOT NULL,
DESCRIPTION VARCHAR2(4000) NOT NULL,
MOD_TIME TIMESTAMP(1) NOT NULL
)
;

CREATE TABLE DP_CREDENTIAL_TYPE
(
ID NUMBER NOT NULL,
NAME VARCHAR2(256) NOT NULL,
INFO_URL VARCHAR2(256),
MOD_TIME TIMESTAMP(1) NOT NULL
)
;

CREATE TABLE DP_EVENT
(
ID NUMBER NOT NULL,
EVENT_NAME VARCHAR2(512),
DP_EVENT_DETAILS VARCHAR2(4000),
MOD_TIME TIMESTAMP(1) NOT NULL
)
;

CREATE TABLE DP_EVENT_LOG
(
ID NUMBER NOT NULL,
USER_ID NUMBER,
EVENT VARCHAR2(512) NOT NULL,
DETAILS VARCHAR2(4000),
MOD_TIME TIMESTAMP(1) NOT NULL
)
;

CREATE TABLE DP_EVENT_LOG_DETAILS
(
ID NUMBER NOT NULL,
EVENT_LOG_ID NUMBER NOT NULL,
DETAILS VARCHAR2(4000),
MOD_TIME TIMESTAMP(1) NOT NULL
)
;

CREATE TABLE DP_FACILITY
(
ID NUMBER NOT NULL,
SHORT_NAME VARCHAR2(256) NOT NULL,
LONG_NAME VARCHAR2(512),
INFO_URL VARCHAR2(256) NOT NULL,
MOD_TIME TIMESTAMP(1) NOT NULL
)
;

CREATE TABLE DP_FACILITY_SESSION
(
ID NUMBER NOT NULL,
DP_SESSION_ID NUMBER,
FACILITY_NAME VARCHAR2(256) NOT NULL,
FACILITY_SESSION_ID VARCHAR2(4000) NOT NULL,
FACILITY_SESSION_ERROR VARCHAR2(4000),
MOD_TIME TIMESTAMP(1) NOT NULL
)
;

CREATE TABLE DP_MODULE_LOOKUP
(
ID NUMBER NOT NULL,
LOCATION VARCHAR2(4000) NOT NULL,
USERNAME VARCHAR2(256),
PASSWORD VARCHAR2(512),
PLATFORM VARCHAR2(4000),
MODULE_TYPE VARCHAR2(256) NOT NULL,
FACILITY VARCHAR2(256) NOT NULL,
ACTIVE VARCHAR2(1),
DATA_IN_FOLDERS VARCHAR2(1),
SPACES_IN_KEYWORDS VARCHAR2(1),
ALL_KEYWORDS VARCHAR2(1),
DPAL_SECURITY VARCHAR2(1) NOT NULL,
MOD_TIME TIMESTAMP(1) NOT NULL
)
;

CREATE TABLE DP_PROXY_SERVERS
(
ID NUMBER NOT NULL,
PROXY_SERVER_ADDRESS VARCHAR2(4000) NOT NULL,
PORT_NUMBER NUMBER NOT NULL,
CA_ROOT_CERTIFICATE VARCHAR2(4000) NOT NULL,
ACTIVE VARCHAR2(1),
MOD_TIME TIMESTAMP(1) NOT NULL
)
;

CREATE TABLE DP_ROLE
(
ID NUMBER NOT NULL,
NAME VARCHAR2(256) NOT NULL,
MOD_TIME TIMESTAMP(1) NOT NULL
)
;

CREATE TABLE DP_SESSION
(
ID NUMBER NOT NULL,
USER_SESSION_ID VARCHAR2(4000) NOT NULL,
USER_ID NUMBER NOT NULL,
CREDENTIAL CLOB NOT NULL,
CREDENTIAL_TYPE VARCHAR2(256),
EXPIRE_DATE_TIME TIMESTAMP(0) NOT NULL,
MOD_TIME TIMESTAMP(1) NOT NULL
)
;

CREATE TABLE DP_USER
(
ID NUMBER NOT NULL,
DN VARCHAR2(4000) NOT NULL,
USER_ID VARCHAR2(255),
MOD_TIME TIMESTAMP(1) NOT NULL
)
;

CREATE TABLE DP_USER_PREFERENCE
(
ID NUMBER NOT NULL,
USER_ID NUMBER,
RESULTS_PER_PAGE NUMBER,
DEFAULT_FACILITY VARCHAR2(4000),
DEFAULT_LOCATION VARCHAR2(4000) NOT NULL,
PROXY_SERVER_ID NUMBER,
RESOLUTION VARCHAR2(256),
EMAIL VARCHAR2(4000),
MOD_TIME TIMESTAMP(1)
)
;

CREATE TABLE DP_USER_ROLE
(
USER_ID NUMBER NOT NULL,
ROLE_ID NUMBER NOT NULL,
COMMENTS VARCHAR2(4000),
MOD_TIME TIMESTAMP(1)
)
;

CREATE TABLE  "SEQUENCE" 
   (	"SEQ_NAME" VARCHAR2(50), 
	"SEQ_COUNT" NUMBER(15,0)
   );


ALTER TABLE DP_CONSTANTS
ADD CONSTRAINT DP_CONSTANTS_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE DP_CONSTANTS
ADD CONSTRAINT DP_CONSTANTS_UK1 UNIQUE
(
NAME
)
 ENABLE
;

ALTER TABLE DP_CREDENTIAL_TYPE
ADD CONSTRAINT DP_CREDENTIAL_TYPE_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE DP_CREDENTIAL_TYPE
ADD CONSTRAINT DP_CREDENTIAL_TYPE_UK1 UNIQUE
(
NAME
)
 ENABLE
;

ALTER TABLE DP_EVENT
ADD CONSTRAINT DP_EVENT_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE DP_EVENT
ADD CONSTRAINT DP_EVENT_UK1 UNIQUE
(
EVENT_NAME
)
 ENABLE
;

ALTER TABLE DP_EVENT_LOG
ADD CONSTRAINT DP_EVENT_LOG_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE DP_EVENT_LOG_DETAILS
ADD CONSTRAINT DP_EVENT_LOG_DETAILS_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE DP_FACILITY
ADD CONSTRAINT DP_FACILITY_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE DP_FACILITY
ADD CONSTRAINT DP_FACILITY_UK1 UNIQUE
(
SHORT_NAME
)
 ENABLE
;

ALTER TABLE DP_FACILITY
ADD CONSTRAINT DP_FACILITY_UK2 UNIQUE
(
LONG_NAME
)
 ENABLE
;

ALTER TABLE DP_FACILITY_SESSION
ADD CONSTRAINT DP_TOKENS_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE DP_MODULE_LOOKUP
ADD CONSTRAINT DP_MODULE_LOOKUP_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE DP_MODULE_LOOKUP
ADD CONSTRAINT DP_MODULE_LOOKUP_UK1 UNIQUE
(
FACILITY
)
 ENABLE
;

ALTER TABLE DP_PROXY_SERVERS
ADD CONSTRAINT DP_PROXY_SERVERS_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE DP_ROLE
ADD CONSTRAINT DP_ROLE_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE DP_ROLE
ADD CONSTRAINT DP_ROLE_UK1 UNIQUE
(
NAME
)
 ENABLE
;

ALTER TABLE DP_SESSION
ADD CONSTRAINT DP_SESSION_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE DP_SESSION
ADD CONSTRAINT DP_SESSION_UK1 UNIQUE
(
USER_SESSION_ID
)
 ENABLE
;

ALTER TABLE DP_USER
ADD CONSTRAINT DP_USER_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE DP_USER
ADD CONSTRAINT DP_USER_UK1 UNIQUE
(
DN
)
 ENABLE
;

ALTER TABLE DP_USER_PREFERENCE
ADD CONSTRAINT DP_USER_PREFERENCE_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE DP_USER_PREFERENCE
ADD CONSTRAINT DP_USER_PREFERENCE_UK1 UNIQUE
(
USER_ID
)
 ENABLE
;

ALTER TABLE DP_USER_ROLE
ADD CONSTRAINT DP_USER_ROLE_PK PRIMARY KEY
(
USER_ID,
ROLE_ID
)
 ENABLE
;

ALTER TABLE DP_EVENT_LOG
ADD CONSTRAINT DP_EVENT_LOG_DP_USER_FK1 FOREIGN KEY
(
USER_ID
)
REFERENCES DP_USER
(
ID
) ENABLE
;

ALTER TABLE DP_EVENT_LOG
ADD CONSTRAINT DP_EVENT_LOG_DP_EVENT_FK1 FOREIGN KEY
(
EVENT
)
REFERENCES DP_EVENT
(
EVENT_NAME
) ENABLE
;

ALTER TABLE DP_EVENT_LOG_DETAILS
ADD CONSTRAINT DP_EVENT_LOG_DETAILS_DP_E_FK1 FOREIGN KEY
(
EVENT_LOG_ID
)
REFERENCES DP_EVENT_LOG
(
ID
) ENABLE
;

ALTER TABLE DP_FACILITY_SESSION
ADD CONSTRAINT DP_TOKENS_DP_SESSION_FK1 FOREIGN KEY
(
DP_SESSION_ID
)
REFERENCES DP_SESSION
(
ID
) ENABLE
;

ALTER TABLE DP_FACILITY_SESSION
ADD CONSTRAINT DP_FACILITY_SESSION_DP_FA_FK1 FOREIGN KEY
(
FACILITY_NAME
)
REFERENCES DP_FACILITY
(
SHORT_NAME
) ENABLE
;

ALTER TABLE DP_MODULE_LOOKUP
ADD CONSTRAINT DP_MODULE_LOOKUP_DP_FACIL_FK1 FOREIGN KEY
(
FACILITY
)
REFERENCES DP_FACILITY
(
SHORT_NAME
) ENABLE
;

ALTER TABLE DP_SESSION
ADD CONSTRAINT DP_SESSION_DP_CREDENTIAL__FK1 FOREIGN KEY
(
CREDENTIAL_TYPE
)
REFERENCES DP_CREDENTIAL_TYPE
(
NAME
) ENABLE
;

ALTER TABLE DP_SESSION
ADD CONSTRAINT DP_SESSION_DP_USER_FK1 FOREIGN KEY
(
USER_ID
)
REFERENCES DP_USER
(
ID
) ENABLE
;

ALTER TABLE DP_USER_PREFERENCE
ADD CONSTRAINT DP_USER_PREFERENCE_DP_USE_FK1 FOREIGN KEY
(
USER_ID
)
REFERENCES DP_USER
(
ID
) ENABLE
;

ALTER TABLE DP_USER_PREFERENCE
ADD CONSTRAINT DP_USER_PREFERENCE_DP_PRO_FK1 FOREIGN KEY
(
PROXY_SERVER_ID
)
REFERENCES DP_PROXY_SERVERS
(
ID
) ENABLE
;

ALTER TABLE DP_USER_PREFERENCE
ADD CONSTRAINT DP_USER_PREFERENCE_DP_FAC_FK1 FOREIGN KEY
(
DEFAULT_FACILITY
)
REFERENCES DP_FACILITY
(
SHORT_NAME
) ENABLE
;

ALTER TABLE DP_USER_ROLE
ADD CONSTRAINT DP_USER_ROLE_DP_USER_FK1 FOREIGN KEY
(
USER_ID
)
REFERENCES DP_USER
(
ID
) ENABLE
;

ALTER TABLE DP_USER_ROLE
ADD CONSTRAINT DP_USER_ROLE_DP_ROLE_FK1 FOREIGN KEY
(
ROLE_ID
)
REFERENCES DP_ROLE
(
ID
) ENABLE
;

COMMENT ON TABLE DP_CONSTANTS IS 'might move to id, name, value, description'
;

COMMENT ON TABLE DP_FACILITY_SESSION IS 'stores the many facility sessions a particular user may have during a dataportal session'
;

COMMENT ON TABLE DP_USER IS 'this identifies the user via their DN'
;

COMMENT ON COLUMN DP_FACILITY_SESSION.DP_SESSION_ID IS 'foreign key linking to dp_session'
;

COMMENT ON COLUMN DP_FACILITY_SESSION.FACILITY_NAME IS 'name of the facility'
;

COMMENT ON COLUMN DP_MODULE_LOOKUP.LOCATION IS 'e.g. for DPAL this would be a Database Connect String and for ACM this might be a Web Services End Point'
;

COMMENT ON COLUMN DP_MODULE_LOOKUP.MODULE_TYPE IS 'e.g. ACM/DPAL'
;

COMMENT ON COLUMN DP_MODULE_LOOKUP.ACTIVE IS 'e.g. if set to null, Y or y  then service is active else it is not'
;

COMMENT ON COLUMN DP_MODULE_LOOKUP.DATA_IN_FOLDERS IS 'if this is set to ''Y'' or ''y'' then the datafile location is actually a directory which holds all the data for the parent dataset. e.g. as used in e-materials with srb locations holding all the data for the datasets.'
;

COMMENT ON COLUMN DP_MODULE_LOOKUP.SPACES_IN_KEYWORDS IS 'if ''Y'' or ''y'' this allows spaces to be present in keywords e.g. in the case of e-minerals and e-materials where spaces are present as keywords are not really keywords but leaf nodes in topic taxanomic structures. This could be used to allow keyphrases also in actual key''words'''
;

COMMENT ON COLUMN DP_MODULE_LOOKUP.ALL_KEYWORDS IS 'if set to ''Y'' or ''y'' this will allow keywords with non-alphanumeric characters to be allowed in the presented keyword list and not suppressed. '
;

COMMENT ON COLUMN DP_MODULE_LOOKUP.DPAL_SECURITY IS 'If this is set to ''Y'' or ''y'' this means that dpal will check the users identification when querying for metadata if this column is any other value then dpal will not check user identification when doing queries.'
;

COMMENT ON COLUMN DP_SESSION.CREDENTIAL_TYPE IS 'e.g. common use is delegated proxy'
;

COMMENT ON COLUMN DP_SESSION.EXPIRE_DATE_TIME IS 'holds a cache of the calculated time that the session expires'
;

COMMENT ON COLUMN DP_USER.USER_ID IS 'e.g. can store the fed-id of the user or the usename used for myproxy - maynot always be available if user uses cert in browser i.e. not logged on via myproxy'
;

COMMENT ON COLUMN DP_USER_PREFERENCE.DEFAULT_LOCATION IS 'show the default result page when user logs in for example all data hierarchy for the investigations that the user has been involved with '
;

COMMENT ON COLUMN DP_USER_PREFERENCE.EMAIL IS 'e-mail address of the user'
;

COMMENT ON COLUMN DP_USER_ROLE.USER_ID IS 'weak entity, many to many mapping table'
;

COMMIT;












