DROP TABLE DP_CONSTANTS CASCADE CONSTRAINTS;
DROP TABLE DP_CREDENTIAL_TYPE CASCADE CONSTRAINTS;
DROP TABLE DP_EVENT CASCADE CONSTRAINTS;
DROP TABLE DP_EVENT_LOG CASCADE CONSTRAINTS;
DROP TABLE DP_EVENT_LOG_DETAILS CASCADE CONSTRAINTS;
DROP TABLE DP_FACILITY CASCADE CONSTRAINTS;
DROP TABLE DP_FACILITY_SESSION CASCADE CONSTRAINTS;
DROP TABLE DP_MODULE_LOOKUP CASCADE CONSTRAINTS;
DROP TABLE DP_PROXY_SERVERS CASCADE CONSTRAINTS;
DROP TABLE DP_ROLE CASCADE CONSTRAINTS;
DROP TABLE DP_SESSION CASCADE CONSTRAINTS;
DROP TABLE DP_USER CASCADE CONSTRAINTS;
DROP TABLE DP_USER_PREFERENCE CASCADE CONSTRAINTS;
DROP TABLE DP_USER_ROLE CASCADE CONSTRAINTS;
DROP TABLE SEQUENCE;
COMMIT
