PROMPT Add a new column to indicate a record has been deleted


ALTER TABLE access_group ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE access_group_dlp ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE access_group_ilp ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE datafile ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE datafile_format ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE datafile_parameter ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE dataset ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE dataset_level_permission ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE dataset_parameter ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE dataset_status ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE dataset_type ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE facility_cycle ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE facility_user ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE instrument ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE investigation ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE investigation_level_permission ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE investigation_type ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE investigator ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE keyword ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE parameter ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE publication ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE related_datafiles ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE sample ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE sample_parameter ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE shift ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE study ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE study_investigation ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE study_status ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE topic ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE topic_list ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE user_access_group ADD deleted VARCHAR2(1) DEFAULT 'N' NOT NULL;



ALTER TABLE ACCESS_GROUP
ADD CONSTRAINT ACCESS_GROUP_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE ACCESS_GROUP_DLP
ADD CONSTRAINT ACCESS_GROUP_DLP_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE ACCESS_GROUP_ILP
ADD CONSTRAINT ACCESS_GROUP_ILP_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE DATAFILE
ADD CONSTRAINT DATAFILE_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE DATAFILE_FORMAT
ADD CONSTRAINT DATAFILE_FORMAT_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE DATAFILE_PARAMETER
ADD CONSTRAINT DATAFILE_PARAMETER_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE DATASET
ADD CONSTRAINT DATASET_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE DATASET_LEVEL_PERMISSION
ADD CONSTRAINT DATASET_LEVEL_PERMISSION_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE DATASET_PARAMETER
ADD CONSTRAINT DATASET_PARAMETER_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE DATASET_STATUS
ADD CONSTRAINT DATASET_STATUS_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE DATASET_TYPE
ADD CONSTRAINT DATASET_TYPE_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE FACILITY_CYCLE
ADD CONSTRAINT FACILITY_CYCLE_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE FACILITY_USER
ADD CONSTRAINT FACILITY_USER_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE INSTRUMENT
ADD CONSTRAINT INSTRUMENT_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE INVESTIGATION
ADD CONSTRAINT INVESTIGATION_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE INVESTIGATION_LEVEL_PERMISSION
ADD CONSTRAINT INVESTIGATION_LEVEL_PERM_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE INVESTIGATION_TYPE
ADD CONSTRAINT INVESTIGATION_TYPE_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE INVESTIGATOR
ADD CONSTRAINT INVESTIGATOR_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE KEYWORD
ADD CONSTRAINT KEYWORD_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE PARAMETER
ADD CONSTRAINT PARAMETER_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE PUBLICATION
ADD CONSTRAINT PUBLICATION_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE RELATED_DATAFILES
ADD CONSTRAINT RELATED_DATAFILES_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE SAMPLE
ADD CONSTRAINT SAMPLE_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE SAMPLE_PARAMETER
ADD CONSTRAINT SAMPLE_PARAMETER_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE SHIFT
ADD CONSTRAINT SHIFT_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE STUDY
ADD CONSTRAINT STUDY_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE STUDY_INVESTIGATION
ADD CONSTRAINT STUDY_INVESTIGATION_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE STUDY_STATUS
ADD CONSTRAINT STUDY_STATUS_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE TOPIC
ADD CONSTRAINT TOPIC_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE TOPIC_LIST
ADD CONSTRAINT TOPIC_LIST_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE USER_ACCESS_GROUP
ADD CONSTRAINT USER_ACCESS_GROUP_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

