REM The following constraints were set up to restrict deletes from the parent
REM table but should actually cascade the delete

PROMPT Enable cascaded deletes

ALTER TABLE ACCESS_GROUP_DLP DROP CONSTRAINT ACCESS_GROUP_DLP_DATASET__FK1;
ALTER TABLE ACCESS_GROUP_DLP
ADD CONSTRAINT ACCESS_GROUP_DLP_DATASET__FK1 FOREIGN KEY
(
DLP_ID
)
REFERENCES DATASET_LEVEL_PERMISSION
(
ID
)
ON DELETE CASCADE ENABLE
;


ALTER TABLE ACCESS_GROUP_ILP DROP CONSTRAINT ACCESS_GROUP_PERMISSION_P_FK1;
ALTER TABLE ACCESS_GROUP_ILP
ADD CONSTRAINT ACCESS_GROUP_PERMISSION_P_FK1 FOREIGN KEY
(
ILP_ID
)
REFERENCES INVESTIGATION_LEVEL_PERMISSION
(
ID
)
ON DELETE CASCADE ENABLE
;



ALTER TABLE DATASET_LEVEL_PERMISSION DROP CONSTRAINT DATASET_PERMISSIONS_DATAS_FK1;
ALTER TABLE DATASET_LEVEL_PERMISSION
ADD CONSTRAINT DATASET_PERMISSIONS_DATAS_FK1 FOREIGN KEY
(
DATASET_ID
)
REFERENCES DATASET
(
ID
)
ON DELETE CASCADE ENABLE
;


ALTER TABLE INVESTIGATION_LEVEL_PERMISSION DROP CONSTRAINT PERMISSION_INVESTIGATION_FK1;
ALTER TABLE INVESTIGATION_LEVEL_PERMISSION
ADD CONSTRAINT PERMISSION_INVESTIGATION_FK1 FOREIGN KEY
(
INVESTIGATION_ID
)
REFERENCES INVESTIGATION
(
ID
)
ON DELETE CASCADE ENABLE
;


ALTER TABLE SHIFT DROP CONSTRAINT SHIFT_INVESTIGATION_FK1;
ALTER TABLE SHIFT
ADD CONSTRAINT SHIFT_INVESTIGATION_FK1 FOREIGN KEY
(
INVESTIGATION_ID
)
REFERENCES INVESTIGATION
(
ID
)
ON DELETE CASCADE ENABLE
;


ALTER TABLE TOPIC_LIST DROP CONSTRAINT FK_TL_STU;
ALTER TABLE TOPIC_LIST
ADD CONSTRAINT FK_TL_STU FOREIGN KEY
(
INVESTIGATION_ID
)
REFERENCES INVESTIGATION
(
ID
)
ON DELETE CASCADE ENABLE
;













