PROMPT New tables to store user roles on each application


CREATE TABLE APPLICATIONS
(
APP_CODE VARCHAR2(10) NOT NULL,
APP_NAME VARCHAR2(255) NOT NULL,
APP_DESCRIPTION VARCHAR2(4000),
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL
)
;

CREATE TABLE USER_ROLES
(
APP_CODE VARCHAR2(10) NOT NULL,
USERNAME VARCHAR2(255) NOT NULL,
ROLE VARCHAR2(20) NOT NULL,
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL
)
;

ALTER TABLE APPLICATIONS
ADD CONSTRAINT APPLICATIONS_PK PRIMARY KEY
(
APP_CODE
)
 ENABLE
;

ALTER TABLE USER_ROLES
ADD CONSTRAINT USER_ROLES_PK PRIMARY KEY
(
APP_CODE,
USERNAME
)
 ENABLE
;

ALTER TABLE USER_ROLES
ADD CONSTRAINT USER_ROLES_APPLICATIONS_FK1 FOREIGN KEY
(
APP_CODE
)
REFERENCES APPLICATIONS
(
APP_CODE
)
ON DELETE CASCADE ENABLE
;

ALTER TABLE APPLICATIONS
ADD CONSTRAINT APPLICATIONS_CHK1 CHECK
(app_code = upper(app_code))
 ENABLE
;

ALTER TABLE USER_ROLES
ADD CONSTRAINT USER_ROLES_CHK1 CHECK
(username = upper(username))
 ENABLE
;

COMMENT ON TABLE APPLICATIONS IS 'Stores descriptions of the applications which use this schema.  This may not be a comprehensive list.'
;

COMMENT ON TABLE USER_ROLES IS 'This table records special roles, eg Administrators, assigned to the users of the applications which access the database.  These users will not necessarily also be facility users.'
;

COMMENT ON COLUMN USER_ROLES.USERNAME IS 'The user''s single-sign-on username.  Must be upper case.'
;

