PROMPT New columns for storing the investigation application form

ALTER TABLE investigation ADD APPLICATION_FORM BLOB;
ALTER TABLE investigation ADD APPLICATION_FORM_MIME_TYPE VARCHAR2(48);
ALTER TABLE investigation ADD APPLICATION_FORM_NAME VARCHAR2(400);


COMMENT ON COLUMN INVESTIGATION.APPLICATION_FORM IS 'The original application document.'
;


ALTER TABLE INVESTIGATION
ADD CONSTRAINT INVESTIGATION_CHK2 CHECK
(APPLICATION_FORM_MIME_TYPE is not null or APPLICATION_FORM is null)
 ENABLE
;

ALTER TABLE INVESTIGATION
ADD CONSTRAINT INVESTIGATION_CHK3 CHECK
(APPLICATION_FORM_NAME is not null or APPLICATION_FORM is null)
 ENABLE
;
