#!/usr/bin/env python

import os
import httplib
from urllib import urlencode
import sys
from optparse import OptionParser
from urlparse import urlparse
import ssl
import logging
import getpass
from suds.client import Client, WebFault
import subprocess
import shlex
try:
    import readline
except:  # Probably windows
    pass

def readServices(path):
    try:
        result = {}
        with open(path) as ss:
            for line in ss.readlines():
                i = line.index(" ")
                key = line[:i].strip()
                value = line[i + 1:].strip()
                result[key] = value
        return result
    except IOError:
        return None

def reportProblem(wf):
    fault = wf.fault
    try:
        exc = wf.fault.detail.IcatException
        fatal(exc.type + " exception: " + exc.message)
    except:
        fatal(fault.faultstring)

def getService(timeout=90):
    hurl = url
    suffix = "/ICATService/ICAT?wsdl"
    if not url.endswith(suffix): hurl = hurl + suffix
 
    client = Client(hurl, timeout=timeout)
    service = client.service
    factory = client.factory
    credentials = factory.create("credentials")
    for i in range (0, len(creds), 2):
        entry = factory.create("credentials.entry")
        entry.key = creds[i]   
        if creds[i + 1] == "-":
            entry.value = getpass.getpass()
        else:
            entry.value = creds[i + 1]
        credentials.entry.append(entry)
    sessionId = service.login(plugin, credentials)
    return client.service, sessionId
 

def getProperties(args):
    parser.set_usage(usagebase + "properties")
    parser.set_description("Display icat properties") 
    options, args = parser.parse_args(args)

    if len(args) > 0:
        fatal("Must have no arguments after the operation 'properties'")

    try:
        service, sessionId = getService()
        for prop in service.getProperties(sessionId): print prop
    except WebFault, wf:
        exc = wf.fault.detail.IcatException
        fatal(exc.type + " exception: " + exc.message)
    except Exception, e:
        fatal(e)
    
    
def search(args):
    parser.set_usage(usagebase + "search <query> [<maxCount> [<entityName>]]")
    parser.set_description("Perform a lucene search")
    options, args = parser.parse_args(args)
    
    query = None
    if len(args) >= 1:
        query = args[0]
        maxCount = 100
        entityName = None
    if len(args) >= 2:
        try:
            maxCount = int(args[1])
        except ValueError as e:
            fatal("'" + args[1] + "' is not an integer")
    if len(args) >= 3:
        entityName = args[2]
    if len(args) > 3 or not query:
        fatal("Must have one, two or three arguments after the operation 'search' - query, maxCount, entityName")

    try:
        service, sessionId = getService()
        print service.luceneSearch(sessionId, query, maxCount, entityName)
    except WebFault, wf:
        reportProblem(wf)
    except Exception, e:
        fatal(e)

def clear(args):
    parser.set_usage(usagebase + "clear")
    parser.set_description("Clear all lucene indices")
    options, args = parser.parse_args(args)

    if len(args) > 0:
        fatal("Must have no arguments after the operation 'clear'")

    try:
        service, sessionId = getService()
        service.luceneClear(sessionId)
    except WebFault, wf:
        exc = wf.fault.detail.IcatException
        fatal(exc.type + " exception: " + exc.message)
    except Exception, e:
        fatal(e)

def commit(args): 
    parser.set_usage(usagebase + "commit")
    parser.set_description("Commit all lucene indices")
    options, args = parser.parse_args(args)

    if len(args) > 0:
        fatal("Must have no arguments after the operation 'commit'")

    try:
        service, sessionId = getService()
        service.luceneCommit(sessionId)
    except WebFault, wf:
        exc = wf.fault.detail.IcatException
        fatal(exc.type + " exception: " + exc.message)
    except Exception, e:
        fatal(e)
        
def getPopulating(args): 
    parser.set_usage(usagebase + "populating")
    parser.set_description("Find entity names in the populate list")
    options, args = parser.parse_args(args)

    if len(args) > 0:
        fatal("Must have no arguments after the operation 'commit'")

    try:
        service, sessionId = getService()
        print service.luceneGetPopulating(sessionId)
    except WebFault, wf:
        exc = wf.fault.detail.IcatException
        fatal(exc.type + " exception: " + exc.message)
    except Exception, e:
        fatal(e)

def populate(args):
    parser.set_usage(usagebase + "populate [<name>]")
    parser.set_description("Populate lucene (for that entry name)")
    options, args = parser.parse_args(args)

    if len(args) == 0: 
        try:
            service, sessionId = getService()
            for entity in service.getEntityNames():
                print entity
                service.lucenePopulate(sessionId, entity)
        except WebFault, wf:
            exc = wf.fault.detail.IcatException
            fatal(exc.type + " exception: " + exc.message)
        except Exception, e:
            fatal(e)
        return    
        
    if len(args) != 1:
        fatal("Must have zero arguments after the operation 'populate' or one - the name of the entity")
 
    try:
        service, sessionId = getService()
        service.lucenePopulate(sessionId, args[0])
    except WebFault, wf:
        exc = wf.fault.detail.IcatException
        fatal(exc.type + " exception: " + exc.message)
    except Exception, e:
        fatal(e)

def help(args):
    parser.set_usage(usagebase + "[subcommand [parameters...] [options...]]")
    parser.set_description("Interact with the ICATAdmin interface. Subcommands are " + str(subcommands.keys()) + 
                            """ All subcommands accept a '-h' or '--help'. """) 
    parser.print_help()

logging.basicConfig(level=logging.CRITICAL)

usagebase = "usage: %prog <url> <username> <password> "
           
subcommands = {}
subcommands["search"] = search
subcommands["properties"] = getProperties
subcommands["populate"] = populate
subcommands["commit"] = commit
subcommands["clear"] = clear
subcommands["populating"] = getPopulating
subcommands["-h"] = help
subcommands["--help"] = help

def fatal(msg):
    print >> sys.stderr, msg
    sys.exit(1)

parser = OptionParser()

try:
    pos = sys.argv.index("--")
    start = sys.argv[1:pos]
    end = sys.argv[pos + 1:]
except ValueError:
    start = sys.argv[1:]
    end = []
 
if len(start) > 2:
    url, plugin = start[:2]
    creds = start[2:]

    if not end:
        
        try:
            service, sessionId = getService()
            service.getProperties(sessionId)
        except Exception, e:
            fatal(e)
       
        print "Use CTRL-D or 'exit' to exit"
        run = True
        while run:
            try:
                command = raw_input("icatadmin> ")
                if command:
                    if command == "exit":
                        run = False
                        continue
                    tokens = shlex.split(command)
                    op = subcommands.get(tokens[0])
                    if not op:
                        print "First argument must be one of " + str(subcommands.keys())
                    else:
                        op(tokens[1:])
            except EOFError:
                print
                sys.exit()
            except:
                pass
        sys.exit()

    op = subcommands.get(end[0])
    if op:
        op(end[1:])
    else:
        fatal("Subcommand " + end[0] + " must be one of " + str(subcommands.keys()))

else:
    fatal("First arguments must be url and plugin mnemonic followed by pairs of arguments to represent the\ncredentials (with '-' to be prompted) optionally followed by '--' and one of\n" + str(subcommands.keys()))
