create index DSPARAMETER_STRING_VALUE on DATASETPARAMETER(STRING_VALUE);
create index DSPARAMETER_NUMERIC_VALUE on DATASETPARAMETER(NUMERIC_VALUE);
create index DSPARAMETER_DATETIME_VALUE on DATASETPARAMETER(DATETIME_VALUE);

create index DFPARAMETER_STRING_VALUE on DATAFILEPARAMETER(STRING_VALUE);
create index DFPARAMETER_NUMERIC_VALUE on DATAFILEPARAMETER(NUMERIC_VALUE);
create index DFPARAMETER_DATETIME_VALUE on DATAFILEPARAMETER(DATETIME_VALUE);

create index INVPARAMETER_STRING_VALUE on INVESTIGATIONPARAMETER(STRING_VALUE);
create index INVPARAMETER_NUMERIC_VALUE on INVESTIGATIONPARAMETER(NUMERIC_VALUE);
create index INVPARAMETER_DATETIME_VALUE on INVESTIGATIONPARAMETER(DATETIME_VALUE);

create index SAMPLEPARAMETER_STRING_VALUE on SAMPLEPARAMETER(STRING_VALUE);
create index SAMPLEPARAMETER_NUMERIC_VALUE on SAMPLEPARAMETER(NUMERIC_VALUE);
create index SAMPLEPARAMETER_DATETIME_VALUE on SAMPLEPARAMETER(DATETIME_VALUE);

create index DATASET_STARTDATE on DATASET(STARTDATE)