CREATE TABLE APPLICATIONS
(
APP_CODE VARCHAR2(10) NOT NULL,
APP_NAME VARCHAR2(255) NOT NULL,
APP_DESCRIPTION VARCHAR2(4000),
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) DEFAULT 'Y' NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE DATAFILE
(
ID NUMBER(38, 0) NOT NULL,
DATASET_ID NUMBER NOT NULL,
NAME VARCHAR2(255) NOT NULL,
DESCRIPTION VARCHAR2(255),
DATAFILE_VERSION VARCHAR2(255),
DATAFILE_VERSION_COMMENT VARCHAR2(4000),
LOCATION VARCHAR2(4000),
DATAFILE_FORMAT VARCHAR2(255),
DATAFILE_FORMAT_VERSION VARCHAR2(255),
DATAFILE_CREATE_TIME TIMESTAMP(1),
DATAFILE_MODIFY_TIME TIMESTAMP(1),
FILE_SIZE NUMBER,
COMMAND VARCHAR2(4000),
CHECKSUM VARCHAR2(255),
SIGNATURE VARCHAR2(4000),
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE DATAFILE_FORMAT
(
NAME VARCHAR2(255) NOT NULL,
VERSION VARCHAR2(255) NOT NULL,
FORMAT_TYPE VARCHAR2(255),
DESCRIPTION VARCHAR2(4000),
SEQ_NUMBER NUMBER DEFAULT 999 NOT NULL,
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE DATAFILE_PARAMETER
(
DATAFILE_ID NUMBER NOT NULL,
NAME VARCHAR2(255) NOT NULL,
UNITS VARCHAR2(255) NOT NULL,
STRING_VALUE VARCHAR2(4000),
NUMERIC_VALUE DOUBLE PRECISION,
RANGE_TOP VARCHAR2(255),
RANGE_BOTTOM VARCHAR2(255),
ERROR VARCHAR2(255),
DESCRIPTION VARCHAR2(4000),
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE DATASET
(
ID NUMBER(38, 0) NOT NULL,
SAMPLE_ID NUMBER,
INVESTIGATION_ID NUMBER NOT NULL,
NAME VARCHAR2(255) NOT NULL,
DATASET_TYPE VARCHAR2(255) NOT NULL,
DATASET_STATUS VARCHAR2(255),
LOCATION VARCHAR2(4000),
DESCRIPTION VARCHAR2(4000),
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE DATASET_PARAMETER
(
DATASET_ID NUMBER NOT NULL,
NAME VARCHAR2(255) NOT NULL,
UNITS VARCHAR2(255) NOT NULL,
STRING_VALUE VARCHAR2(4000),
NUMERIC_VALUE DOUBLE PRECISION,
RANGE_TOP VARCHAR2(255),
RANGE_BOTTOM VARCHAR2(255),
ERROR VARCHAR2(255),
DESCRIPTION VARCHAR2(4000),
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE DATASET_STATUS
(
NAME VARCHAR2(255) NOT NULL,
DESCRIPTION VARCHAR2(4000),
SEQ_NUMBER NUMBER DEFAULT 999 NOT NULL,
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(4000) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE DATASET_TYPE
(
NAME VARCHAR2(255) NOT NULL,
DESCRIPTION VARCHAR2(4000),
SEQ_NUMBER NUMBER DEFAULT 999 NOT NULL,
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE FACILITY_CYCLE
(
NAME VARCHAR2(255) NOT NULL,
START_DATE TIMESTAMP(1),
FINISH_DATE TIMESTAMP(1),
DESCRIPTION VARCHAR2(4000),
SEQ_NUMBER NUMBER DEFAULT 999 NOT NULL,
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE FACILITY_INSTRUMENT_SCIENTIST
(
INSTRUMENT_NAME VARCHAR2(255) NOT NULL,
FEDERAL_ID VARCHAR2(255) NOT NULL,
SEQ_NUMBER NUMBER DEFAULT 999 NOT NULL,
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE FACILITY_USER
(
FACILITY_USER_ID VARCHAR2(255) NOT NULL,
FEDERAL_ID VARCHAR2(255),
TITLE VARCHAR2(255),
INITIALS VARCHAR2(255),
FIRST_NAME VARCHAR2(255),
MIDDLE_NAME VARCHAR2(255),
LAST_NAME VARCHAR2(255),
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE ICAT_AUTHORISATION
(
ID NUMBER NOT NULL,
USER_ID VARCHAR2(255) NOT NULL,
ROLE VARCHAR2(255) NOT NULL,
USER_CHILD_RECORD NUMBER,
ELEMENT_TYPE VARCHAR2(100) NOT NULL,
ELEMENT_ID NUMBER,
PARENT_ELEMENT_TYPE VARCHAR2(100),
PARENT_ELEMENT_ID NUMBER,
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) DEFAULT 'Y' NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE ICAT_ROLE
(
ROLE VARCHAR2(255) NOT NULL,
ROLE_WEIGHT NUMBER NOT NULL,
ACTION_INSERT VARCHAR2(1) DEFAULT 'N' NOT NULL,
ACTION_INSERT_WEIGHT NUMBER NOT NULL,
ACTION_SELECT VARCHAR2(1) DEFAULT 'N' NOT NULL,
ACTION_SELECT_WEIGHT NUMBER NOT NULL,
ACTION_DOWNLOAD VARCHAR2(1) DEFAULT 'N' NOT NULL,
ACTION_DOWNLOAD_WEIGHT NUMBER NOT NULL,
ACTION_UPDATE VARCHAR2(1) DEFAULT 'N' NOT NULL,
ACTION_UPDATE_WEIGHT NUMBER NOT NULL,
ACTION_DELETE VARCHAR2(1) DEFAULT 'N' NOT NULL,
ACTION_DELETE_WEIGHT NUMBER NOT NULL,
ACTION_REMOVE VARCHAR2(1) DEFAULT 'N' NOT NULL,
ACTION_REMOVE_WEIGHT NUMBER NOT NULL,
ACTION_ROOT_INSERT VARCHAR2(1) DEFAULT 'N' NOT NULL,
ACTION_ROOT_INSERT_WEIGHT NUMBER NOT NULL,
ACTION_ROOT_REMOVE VARCHAR2(1) DEFAULT 'N' NOT NULL,
ACTION_ROOT_REMOVE_WEIGHT NUMBER NOT NULL,
ACTION_SET_FA VARCHAR2(1) DEFAULT 'N' NOT NULL,
ACTION_SET_FA_WEIGHT NUMBER NOT NULL,
ACTION_MANAGE_USERS VARCHAR2(1) DEFAULT 'N' NOT NULL,
ACTION_MANAGE_USERS_WEIGHT NUMBER NOT NULL,
ACTION_SUPER VARCHAR2(1) DEFAULT 'N' NOT NULL,
ACTION_SUPER_WEIGHT NUMBER NOT NULL,
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) DEFAULT 'Y' NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE INSTRUMENT
(
NAME VARCHAR2(255) NOT NULL,
SHORT_NAME VARCHAR2(30) NOT NULL,
TYPE VARCHAR2(255),
DESCRIPTION VARCHAR2(4000),
SEQ_NUMBER NUMBER DEFAULT 999 NOT NULL,
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE INVESTIGATION
(
ID NUMBER(38, 0) NOT NULL,
INV_NUMBER VARCHAR2(255) NOT NULL,
VISIT_ID VARCHAR2(255),
FACILITY VARCHAR2(30) NOT NULL,
FACILITY_CYCLE VARCHAR2(255),
INSTRUMENT VARCHAR2(255),
TITLE VARCHAR2(255) NOT NULL,
INV_TYPE VARCHAR2(255) NOT NULL,
INV_ABSTRACT VARCHAR2(4000),
PREV_INV_NUMBER VARCHAR2(255),
BCAT_INV_STR VARCHAR2(255),
GRANT_ID NUMBER,
INV_PARAM_NAME VARCHAR2(255),
INV_PARAM_VALUE VARCHAR2(4000),
INV_START_DATE TIMESTAMP(1),
INV_END_DATE TIMESTAMP(1),
RELEASE_DATE TIMESTAMP(1),
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL,
SRC_HASH VARCHAR2(32)
)
;

CREATE TABLE INVESTIGATION_TYPE
(
NAME VARCHAR2(255) NOT NULL,
DESCRIPTION VARCHAR2(4000),
SEQ_NUMBER NUMBER DEFAULT 999 NOT NULL,
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE INVESTIGATOR
(
INVESTIGATION_ID NUMBER(38, 0) NOT NULL,
FACILITY_USER_ID VARCHAR2(255) NOT NULL,
ROLE VARCHAR2(255),
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE KEYWORD
(
INVESTIGATION_ID NUMBER(38, 0) NOT NULL,
NAME VARCHAR2(255) NOT NULL,
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE PARAMETER
(
NAME VARCHAR2(255) NOT NULL,
UNITS VARCHAR2(255) NOT NULL,
UNITS_LONG_VERSION VARCHAR2(4000),
SEARCHABLE VARCHAR2(1) NOT NULL,
NUMERIC_VALUE VARCHAR2(1) NOT NULL,
NON_NUMERIC_VALUE_FORMAT VARCHAR2(255),
IS_SAMPLE_PARAMETER VARCHAR2(1) NOT NULL,
IS_DATASET_PARAMETER VARCHAR2(1) NOT NULL,
IS_DATAFILE_PARAMETER VARCHAR2(1) NOT NULL,
DESCRIPTION VARCHAR2(4000),
VERIFIED VARCHAR2(1) NOT NULL,
SEQ_NUMBER NUMBER DEFAULT 999 NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
MOD_TIME TIMESTAMP(1) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE PUBLICATION
(
ID NUMBER NOT NULL,
INVESTIGATION_ID NUMBER(38, 0) NOT NULL,
FULL_REFERENCE VARCHAR2(4000) NOT NULL,
URL VARCHAR2(255),
REPOSITORY_ID VARCHAR(4000),
REPOSITORY VARCHAR2(255),
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE RELATED_DATAFILES
(
SOURCE_DATAFILE_ID NUMBER NOT NULL,
DEST_DATAFILE_ID NUMBER NOT NULL,
RELATION VARCHAR2(255) NOT NULL,
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE SAMPLE
(
ID NUMBER(38, 0) NOT NULL,
INVESTIGATION_ID NUMBER NOT NULL,
NAME VARCHAR2(255) NOT NULL,
INSTANCE VARCHAR2(255),
CHEMICAL_FORMULA VARCHAR2(255),
SAFETY_INFORMATION VARCHAR2(4000) NOT NULL,
PROPOSAL_SAMPLE_ID NUMBER(38, 0),
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE SAMPLE_PARAMETER
(
SAMPLE_ID NUMBER(38, 0) NOT NULL,
NAME VARCHAR2(255) NOT NULL,
UNITS VARCHAR2(255) NOT NULL,
STRING_VALUE VARCHAR2(4000),
NUMERIC_VALUE DOUBLE PRECISION,
ERROR VARCHAR2(255),
RANGE_TOP VARCHAR2(255),
RANGE_BOTTOM VARCHAR2(255),
DESCRIPTION VARCHAR2(4000),
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE SHIFT
(
INVESTIGATION_ID NUMBER NOT NULL,
START_DATE TIMESTAMP(1) NOT NULL,
END_DATE TIMESTAMP(1) NOT NULL,
SHIFT_COMMENT VARCHAR2(4000),
MOD_ID VARCHAR2(255) NOT NULL,
MOD_TIME TIMESTAMP(1) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE SOFTWARE_VERSION
(
ID NUMBER(38, 0) NOT NULL,
NAME VARCHAR(4000),
SW_VERSION VARCHAR2(255),
FEATURES VARCHAR2(255),
DESCRIPTION VARCHAR2(255),
AUTHORS VARCHAR2(255),
SEQ_NUMBER NUMBER DEFAULT 999 NOT NULL,
MOD_TIME TIMESTAMP NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE STUDY
(
ID NUMBER(38, 0) NOT NULL,
NAME VARCHAR2(255) NOT NULL,
PURPOSE VARCHAR2(4000),
STATUS VARCHAR2(255),
RELATED_MATERIAL VARCHAR2(4000),
STUDY_CREATION_DATE TIMESTAMP(1),
STUDY_MANAGER NUMBER,
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE STUDY_INVESTIGATION
(
STUDY_ID NUMBER NOT NULL,
INVESTIGATION_ID NUMBER NOT NULL,
INVESTIGATION_VISIT_ID VARCHAR2(255) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
MOD_TIME TIMESTAMP(1) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE STUDY_STATUS
(
NAME VARCHAR2(255) NOT NULL,
DESCRIPTION VARCHAR2(4000) NOT NULL,
SEQ_NUMBER NUMBER DEFAULT 999 NOT NULL,
MOD_TIME TIMESTAMP NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE THIS_ICAT
(
FACILITY_SHORT_NAME VARCHAR2(30) NOT NULL,
FACILITY_LONG_NAME VARCHAR2(255),
FACILITY_URL VARCHAR2(255),
FACILITY_DESCRIPTION VARCHAR2(4000),
DAYS_UNTIL_PUBLIC_RELEASE NUMBER(7, 0) DEFAULT 1095 NOT NULL,
SEQ_NUMBER NUMBER DEFAULT 999 NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
MOD_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) DEFAULT 'Y' NOT NULL
)
;

CREATE TABLE TOPIC
(
ID NUMBER(38, 0) NOT NULL,
NAME VARCHAR2(255),
PARENT_ID NUMBER(38, 0),
TOPIC_LEVEL NUMBER(38, 0),
MOD_TIME TIMESTAMP NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE TOPIC_LIST
(
INVESTIGATION_ID NUMBER(38, 0) NOT NULL,
TOPIC_ID NUMBER(38, 0) NOT NULL,
MOD_TIME DATE,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

CREATE TABLE USER_ROLES
(
APP_CODE VARCHAR2(10) NOT NULL,
USERNAME VARCHAR2(255) NOT NULL,
ROLE VARCHAR2(20) NOT NULL,
MOD_TIME TIMESTAMP(1) NOT NULL,
MOD_ID VARCHAR2(255) NOT NULL,
CREATE_TIME TIMESTAMP(1) NOT NULL,
CREATE_ID VARCHAR2(255) NOT NULL,
FACILITY_ACQUIRED VARCHAR2(1) DEFAULT 'Y' NOT NULL,
DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
)
;

ALTER TABLE APPLICATIONS 
ADD CONSTRAINT APPLICATIONS_PK PRIMARY KEY
(
APP_CODE
)
 ENABLE
;

ALTER TABLE DATAFILE 
ADD CONSTRAINT PK_DF PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE DATAFILE_FORMAT 
ADD PRIMARY KEY
(
NAME,
VERSION
)
 ENABLE
;

ALTER TABLE DATAFILE_PARAMETER 
ADD CONSTRAINT PK_DP PRIMARY KEY
(
DATAFILE_ID,
NAME,
UNITS
)
 ENABLE
;

ALTER TABLE DATASET 
ADD CONSTRAINT PK_DS PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE DATASET 
ADD CONSTRAINT DATASET_UK1 UNIQUE
(
INVESTIGATION_ID,
SAMPLE_ID,
DATASET_TYPE,
NAME
)
 ENABLE
;

ALTER TABLE DATASET_PARAMETER 
ADD CONSTRAINT PK_CP PRIMARY KEY
(
DATASET_ID,
NAME,
UNITS
)
 ENABLE
;

ALTER TABLE DATASET_STATUS 
ADD PRIMARY KEY
(
NAME
)
 ENABLE
;

ALTER TABLE DATASET_TYPE 
ADD PRIMARY KEY
(
NAME
)
 ENABLE
;

ALTER TABLE FACILITY_CYCLE 
ADD PRIMARY KEY
(
NAME
)
 ENABLE
;

ALTER TABLE FACILITY_INSTRUMENT_SCIENTIST 
ADD CONSTRAINT FACILITY_INSTRUMENT_SCIEN_PK PRIMARY KEY
(
INSTRUMENT_NAME,
FEDERAL_ID
)
 ENABLE
;

ALTER TABLE FACILITY_USER 
ADD CONSTRAINT FACILITY_USER_PK PRIMARY KEY
(
FACILITY_USER_ID
)
 ENABLE
;

ALTER TABLE ICAT_AUTHORISATION 
ADD CONSTRAINT ICAT_AUTHORISATION_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE ICAT_AUTHORISATION 
ADD CONSTRAINT ICAT_AUTHORISATION_UK1 UNIQUE
(
USER_ID,
ELEMENT_TYPE,
ELEMENT_ID,
PARENT_ELEMENT_TYPE,
PARENT_ELEMENT_ID
)
 ENABLE
;

ALTER TABLE ICAT_ROLE 
ADD CONSTRAINT ICAT_ROLE_PK PRIMARY KEY
(
ROLE
)
 ENABLE
;

ALTER TABLE ICAT_ROLE  
ADD CONSTRAINT ICAT_ROLE_UK1 UNIQUE
(
ACTION_INSERT,
ACTION_SELECT,
ACTION_DOWNLOAD,
ACTION_UPDATE,
ACTION_DELETE,
ACTION_REMOVE,
ACTION_ROOT_INSERT,
ACTION_ROOT_REMOVE,
ACTION_SET_FA,
ACTION_MANAGE_USERS,
ACTION_SUPER
)
 ENABLE
;

ALTER TABLE INSTRUMENT 
ADD CONSTRAINT INSTRUMENT_TYPE_PK PRIMARY KEY
(
NAME
)
 ENABLE
;

ALTER TABLE INVESTIGATION 
ADD CONSTRAINT PK_I PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE INVESTIGATION 
ADD CONSTRAINT INVESTIGATION_UK2 UNIQUE
(
VISIT_ID,
INV_NUMBER,
FACILITY_CYCLE,
INSTRUMENT
)
 ENABLE
;

ALTER TABLE INVESTIGATION 
ADD CONSTRAINT INVESTIGATION_UK3 UNIQUE
(
SRC_HASH
)
 ENABLE
;

ALTER TABLE INVESTIGATION_TYPE 
ADD PRIMARY KEY
(
NAME
)
 ENABLE
;

ALTER TABLE INVESTIGATOR 
ADD CONSTRAINT PK_INVR PRIMARY KEY
(
INVESTIGATION_ID,
FACILITY_USER_ID
)
 ENABLE
;

ALTER TABLE KEYWORD 
ADD CONSTRAINT KEYWORD_PK PRIMARY KEY
(
INVESTIGATION_ID,
NAME
)
 ENABLE
;

ALTER TABLE PARAMETER 
ADD CONSTRAINT PARAMETER_PK PRIMARY KEY
(
NAME,
UNITS
)
 ENABLE
;

ALTER TABLE PUBLICATION 
ADD CONSTRAINT PK_P PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE RELATED_DATAFILES 
ADD CONSTRAINT PK_FGDF PRIMARY KEY
(
SOURCE_DATAFILE_ID,
DEST_DATAFILE_ID
)
 ENABLE
;

ALTER TABLE SAMPLE 
ADD CONSTRAINT PK_S PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE SAMPLE 
ADD CONSTRAINT SAMPLE_UK1 UNIQUE
(
INVESTIGATION_ID,
NAME,
INSTANCE
)
 ENABLE
;

ALTER TABLE SAMPLE 
ADD CONSTRAINT SAMPLE_UK2 UNIQUE
(
ID,
INVESTIGATION_ID
)
 ENABLE
;

ALTER TABLE SAMPLE_PARAMETER 
ADD CONSTRAINT PK_SP PRIMARY KEY
(
SAMPLE_ID,
NAME,
UNITS
)
 ENABLE
;

ALTER TABLE SHIFT 
ADD CONSTRAINT SHIFT_PK PRIMARY KEY
(
INVESTIGATION_ID,
START_DATE,
END_DATE
)
 ENABLE
;

ALTER TABLE SOFTWARE_VERSION 
ADD PRIMARY KEY
(
ID
)
 ENABLE
;
 
ALTER TABLE STUDY 
ADD CONSTRAINT PK_STU PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE STUDY 
ADD CONSTRAINT STUDY_UK1 UNIQUE
(
NAME
)
 ENABLE
;

ALTER TABLE STUDY_INVESTIGATION 
ADD CONSTRAINT STUD_INVESTIGATION_PK PRIMARY KEY
(
STUDY_ID,
INVESTIGATION_ID
)
 ENABLE
;

ALTER TABLE STUDY_STATUS 
ADD PRIMARY KEY
(
NAME
)
 ENABLE
;

ALTER TABLE THIS_ICAT 
ADD CONSTRAINT THIS_ICAT_PK PRIMARY KEY
(
FACILITY_SHORT_NAME
)
 ENABLE
;

ALTER TABLE TOPIC 
ADD CONSTRAINT PK_T PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE TOPIC_LIST 
ADD CONSTRAINT PK_TL PRIMARY KEY
(
INVESTIGATION_ID,
TOPIC_ID
)
 ENABLE
;

ALTER TABLE USER_ROLES 
ADD CONSTRAINT USER_ROLES_PK PRIMARY KEY
(
APP_CODE,
USERNAME
)
 ENABLE
;

ALTER TABLE DATAFILE 
ADD CONSTRAINT DATAFILE_DATASET_FK1 FOREIGN KEY
(
DATASET_ID
)
REFERENCES DATASET
(
ID
) ENABLE
;

ALTER TABLE DATAFILE 
ADD CONSTRAINT DATAFILE_DATAFILE_FORMAT_FK1 FOREIGN KEY
(
DATAFILE_FORMAT,
DATAFILE_FORMAT_VERSION
)
REFERENCES DATAFILE_FORMAT 
(
NAME,
VERSION
) ENABLE
;

ALTER TABLE DATAFILE_PARAMETER 
ADD CONSTRAINT FK_DP_DF FOREIGN KEY
(
DATAFILE_ID
)
REFERENCES DATAFILE
(
ID
)
ON DELETE CASCADE ENABLE
;

ALTER TABLE DATAFILE_PARAMETER 
ADD CONSTRAINT DATAFILE_PARAMETER_PARAME_FK1 FOREIGN KEY
(
NAME,
UNITS
)
REFERENCES PARAMETER
(
NAME,
UNITS
) ENABLE
;

ALTER TABLE DATASET 
ADD CONSTRAINT DATASET_SAMPLE_FK1 FOREIGN KEY
(
SAMPLE_ID,
INVESTIGATION_ID
)
REFERENCES SAMPLE
(
ID,
INVESTIGATION_ID
) ENABLE
;

ALTER TABLE DATASET 
ADD CONSTRAINT DATASET_DATASET_TYPE_FK1 FOREIGN KEY
(
DATASET_TYPE
)
REFERENCES DATASET_TYPE
(
NAME
) ENABLE
;

ALTER TABLE DATASET 
ADD CONSTRAINT DATASET_DATASET_STATUS_FK1 FOREIGN KEY
(
DATASET_STATUS
)
REFERENCES DATASET_STATUS
(
NAME
) ENABLE
;

ALTER TABLE DATASET 
ADD CONSTRAINT DATASET_INVESTIGATION_FK1 FOREIGN KEY
(
INVESTIGATION_ID
)
REFERENCES INVESTIGATION
(
ID
) ENABLE
;

ALTER TABLE DATASET_PARAMETER 
ADD CONSTRAINT FK_CP_C FOREIGN KEY
(
DATASET_ID
)
REFERENCES DATASET
(
ID
)
ON DELETE CASCADE ENABLE
;

ALTER TABLE DATASET_PARAMETER 
ADD CONSTRAINT DATASET_PARAMETER_PARAMET_FK1 FOREIGN KEY
(
NAME,
UNITS
)
REFERENCES PARAMETER
(
NAME,
UNITS
) ENABLE
;

ALTER TABLE FACILITY_INSTRUMENT_SCIENTIST 
ADD CONSTRAINT FACILITY_INSTRUMENT_SCIEN_FK1 FOREIGN KEY
(
INSTRUMENT_NAME
)
REFERENCES INSTRUMENT
(
NAME
) ENABLE
;

ALTER TABLE ICAT_AUTHORISATION  
ADD CONSTRAINT ICAT_AUTHORISATION_ICAT_R_FK1 FOREIGN KEY
(
ROLE
)
REFERENCES ICAT_ROLE
(
ROLE
) ENABLE
;

ALTER TABLE INVESTIGATION  
ADD CONSTRAINT INVESTIGATION_INVESTIGATI_FK1 FOREIGN KEY
(
INV_TYPE
)
REFERENCES INVESTIGATION_TYPE
(
NAME
) ENABLE
;

ALTER TABLE INVESTIGATION 
ADD CONSTRAINT INVESTIGATION_FACILITY_CY_FK1 FOREIGN KEY
(
FACILITY_CYCLE
)
REFERENCES FACILITY_CYCLE
(
NAME
) ENABLE
;

ALTER TABLE INVESTIGATION 
ADD CONSTRAINT INVESTIGATION_INSTRUMENT_FK1 FOREIGN KEY
(
INSTRUMENT
)
REFERENCES INSTRUMENT
(
NAME
) ENABLE
;

ALTER TABLE INVESTIGATION 
ADD CONSTRAINT INVESTIGATION_THIS_ICAT_FK1 FOREIGN KEY
(
FACILITY
)
REFERENCES THIS_ICAT
(
FACILITY_SHORT_NAME
) ENABLE
;

ALTER TABLE INVESTIGATOR 
ADD CONSTRAINT INVESTIGATOR_FACILITY_USER_FK1 FOREIGN KEY
(
FACILITY_USER_ID
)
REFERENCES FACILITY_USER
(
FACILITY_USER_ID
) ENABLE
;

ALTER TABLE INVESTIGATOR 
ADD CONSTRAINT FK_I_I FOREIGN KEY
(
INVESTIGATION_ID
)
REFERENCES INVESTIGATION
(
ID
)
ON DELETE CASCADE ENABLE
;

ALTER TABLE KEYWORD 
ADD CONSTRAINT FK_K_STU FOREIGN KEY
(
INVESTIGATION_ID
)
REFERENCES INVESTIGATION
(
ID
)
ON DELETE CASCADE ENABLE
;

ALTER TABLE PUBLICATION 
ADD CONSTRAINT FK_P_I FOREIGN KEY
(
INVESTIGATION_ID
)
REFERENCES INVESTIGATION
(
ID
)
ON DELETE CASCADE ENABLE
;

ALTER TABLE RELATED_DATAFILES 
ADD CONSTRAINT FK_FGDF_DF FOREIGN KEY
(
SOURCE_DATAFILE_ID
)
REFERENCES DATAFILE
(
ID
) ENABLE
;

ALTER TABLE RELATED_DATAFILES 
ADD CONSTRAINT RELATED_DATAFILES_DATAFIL_FK1 FOREIGN KEY
(
DEST_DATAFILE_ID
)
REFERENCES DATAFILE
(
ID
) ENABLE
;

ALTER TABLE SAMPLE 
ADD CONSTRAINT FK_S_I FOREIGN KEY
(
INVESTIGATION_ID
)
REFERENCES INVESTIGATION
(
ID
)
ON DELETE CASCADE ENABLE
;

ALTER TABLE SAMPLE_PARAMETER 
ADD CONSTRAINT FK_S FOREIGN KEY
(
SAMPLE_ID
)
REFERENCES SAMPLE
(
ID
)
ON DELETE CASCADE ENABLE
;

ALTER TABLE SAMPLE_PARAMETER  
ADD CONSTRAINT SAMPLE_PARAMETER_PARAMETE_FK1 FOREIGN KEY
(
NAME,
UNITS
)
REFERENCES PARAMETER
(
NAME,
UNITS
) ENABLE
;

ALTER TABLE SHIFT 
ADD CONSTRAINT SHIFT_INVESTIGATION_FK1 FOREIGN KEY
(
INVESTIGATION_ID
)
REFERENCES INVESTIGATION
(
ID
)
ON DELETE CASCADE ENABLE
;

ALTER TABLE STUDY 
ADD CONSTRAINT STUDY_STUDY_STATUS_FK1 FOREIGN KEY
(
STATUS
)
REFERENCES STUDY_STATUS
(
NAME
) ENABLE
;

ALTER TABLE STUDY_INVESTIGATION 
ADD CONSTRAINT STUD_INVESTIGATION_STUDY_FK1 FOREIGN KEY
(
STUDY_ID
)
REFERENCES STUDY
(
ID
) ENABLE
;

ALTER TABLE STUDY_INVESTIGATION 
ADD CONSTRAINT STUD_INVESTIGATION_INVEST_FK1 FOREIGN KEY
(
STUDY_ID
)
REFERENCES INVESTIGATION
(
ID
) ENABLE
;

ALTER TABLE TOPIC_LIST 
ADD CONSTRAINT FK_TL_STU FOREIGN KEY
(
INVESTIGATION_ID
)
REFERENCES INVESTIGATION
(
ID
)
ON DELETE CASCADE ENABLE
;

ALTER TABLE TOPIC_LIST 
ADD CONSTRAINT FK_TL_T FOREIGN KEY
(
TOPIC_ID
)
REFERENCES TOPIC
(
ID
) ENABLE
;

ALTER TABLE USER_ROLES 
ADD CONSTRAINT USER_ROLES_APPLICATIONS_FK1 FOREIGN KEY
(
APP_CODE
)
REFERENCES APPLICATIONS
(
APP_CODE
)
ON DELETE CASCADE ENABLE
;

ALTER TABLE APPLICATIONS 
ADD CONSTRAINT APPLICATIONS_CHK1 CHECK
(app_code = upper(app_code))
 ENABLE
;

ALTER TABLE DATAFILE 
ADD CONSTRAINT DATAFILE_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE DATAFILE 
ADD CONSTRAINT DATAFILE_CHK2 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;

ALTER TABLE DATAFILE_FORMAT 
ADD CONSTRAINT DATAFILE_FORMAT_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE DATAFILE_FORMAT 
ADD CONSTRAINT DATAFILE_FORMAT_CHK2 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;

ALTER TABLE DATAFILE_PARAMETER 
ADD CONSTRAINT DATAFILE_PARAMETER_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE DATAFILE_PARAMETER 
ADD CONSTRAINT DATAFILE_PARAMETER_CHK2 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;

ALTER TABLE DATASET 
ADD CONSTRAINT DATASET_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE DATASET 
ADD CONSTRAINT DATASET_CHK2 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;

ALTER TABLE DATASET_PARAMETER 
ADD CONSTRAINT DATASET_PARAMETER_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE DATASET_PARAMETER 
ADD CONSTRAINT DATASET_PARAMETER_CHK2 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;

ALTER TABLE DATASET_STATUS 
ADD CONSTRAINT DATASET_STATUS_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE DATASET_STATUS 
ADD CONSTRAINT DATASET_STATUS_CHK2 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;

ALTER TABLE DATASET_TYPE 
ADD CONSTRAINT DATASET_TYPE_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE DATASET_TYPE 
ADD CONSTRAINT DATASET_TYPE_CHK2 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;

ALTER TABLE FACILITY_CYCLE 
ADD CONSTRAINT FACILITY_CYCLE_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE FACILITY_CYCLE 
ADD CONSTRAINT FACILITY_CYCLE_CHK2 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;

ALTER TABLE FACILITY_USER 
ADD CONSTRAINT FACILITY_USER_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;
 
ALTER TABLE FACILITY_USER 
ADD CONSTRAINT FACILITY_USER_CHK2 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;

ALTER TABLE INSTRUMENT 
ADD CONSTRAINT INSTRUMENT_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE INSTRUMENT 
ADD CONSTRAINT INSTRUMENT_CHK2 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;

ALTER TABLE INVESTIGATION 
ADD CONSTRAINT INVESTIGATION_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE INVESTIGATION 
ADD CONSTRAINT INVESTIGATION_CHK4 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;

ALTER TABLE INVESTIGATION_TYPE 
ADD CONSTRAINT INVESTIGATION_TYPE_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE INVESTIGATION_TYPE 
ADD CONSTRAINT INVESTIGATION_TYPE_CHK2 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;

ALTER TABLE INVESTIGATOR 
ADD CONSTRAINT INVESTIGATOR_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE INVESTIGATOR 
ADD CONSTRAINT INVESTIGATOR_CHK2 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;

ALTER TABLE KEYWORD 
ADD CONSTRAINT KEYWORD_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE KEYWORD 
ADD CONSTRAINT KEYWORD_CHK2 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;

ALTER TABLE PARAMETER 
ADD CONSTRAINT PARAMETER_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE PARAMETER 
ADD CONSTRAINT PARAMETER_CHK2 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;

ALTER TABLE PUBLICATION 
ADD CONSTRAINT PUBLICATION_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE PUBLICATION 
ADD CONSTRAINT PUBLICATION_CHK2 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;

ALTER TABLE RELATED_DATAFILES 
ADD CONSTRAINT RELATED_DATAFILES_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE RELATED_DATAFILES 
ADD CONSTRAINT RELATED_DATAFILES_CHK2 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;

ALTER TABLE SAMPLE 
ADD CONSTRAINT SAMPLE_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE SAMPLE 
ADD CONSTRAINT SAMPLE_CHK2 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;

ALTER TABLE SAMPLE_PARAMETER 
ADD CONSTRAINT SAMPLE_PARAMETER_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE SAMPLE_PARAMETER 
ADD CONSTRAINT SAMPLE_PARAMETER_CHK2 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;

ALTER TABLE SHIFT 
ADD CONSTRAINT SHIFT_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE SHIFT 
ADD CONSTRAINT SHIFT_CHK2 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;

ALTER TABLE STUDY 
ADD CONSTRAINT STUDY_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE STUDY 
ADD CONSTRAINT STUDY_CHK2 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;

ALTER TABLE STUDY_INVESTIGATION 
ADD CONSTRAINT STUDY_INVESTIGATION_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE STUDY_INVESTIGATION 
ADD CONSTRAINT STUDY_INVESTIGATION_CHK2 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;

ALTER TABLE STUDY_STATUS 
ADD CONSTRAINT STUDY_STATUS_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE STUDY_STATUS 
ADD CONSTRAINT STUDY_STATUS_CHK2 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;

ALTER TABLE TOPIC 
ADD CONSTRAINT TOPIC_CHK1 CHECK 
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE TOPIC 
ADD CONSTRAINT TOPIC_CHK2 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;

ALTER TABLE TOPIC_LIST 
ADD CONSTRAINT TOPIC_LIST_CHK1 CHECK
(deleted in('Y','N'))
 ENABLE
;

ALTER TABLE TOPIC_LIST 
ADD CONSTRAINT TOPIC_LIST_CHK2 CHECK
(Facility_Acquired in('Y','N'))
 ENABLE
;
 
ALTER TABLE USER_ROLES 
ADD CONSTRAINT USER_ROLES_CHK1 CHECK
(username = upper(username))
 ENABLE
;

CREATE INDEX DATAFILE_INDEX1 ON DATAFILE (dataset_id);

CREATE INDEX KEYWORD_INDEX1 ON KEYWORD (INVESTIGATION_ID);

COMMENT ON TABLE APPLICATIONS IS 'Stores descriptions of the applications which use this schema.  This may not be a comprehensive list.'
;

COMMENT ON TABLE DATAFILE IS 'this use to contain the uA hours column which gave the ISIS scientists an idea of how much data was collected. this has been moved to being a dataset parameter specific to ISIS.'
;

COMMENT ON TABLE DATASET_PARAMETER IS 'This can be used for  1) holding instrument configuration parameters relevent for this dataset (ISIS note: instrument configuration usually only happen once per cycle so this might attach to datasets associated with the calibration investigation) '
;

COMMENT ON TABLE FACILITY_USER IS 'Associates facility user ids with their federal ids'
;

COMMENT ON TABLE ICAT_AUTHORISATION IS 'contains authorisation information pertaining to user and their roles'
;

COMMENT ON TABLE INVESTIGATOR IS 'A user can be in more than one investigation and and investigation can have more than one user. This is achieved by having facility_user_id and investigation_id as a composite primary key.'
;

COMMENT ON TABLE PARAMETER IS 'This table contains information about the valid parameters that can be used to describe samples, datasets & datafiles.  puposefully this table has been setup such that a paramater is only stored using one unit systems (all conversion should occur elsewhere).'
;

COMMENT ON TABLE PUBLICATION IS 'This can support pointing to supporting publications in any arbitary repository'
;

COMMENT ON TABLE RELATED_DATAFILES IS 'There can only be one relationship between any two specified files.'
;

COMMENT ON TABLE SAMPLE IS 'This table stores the sample information for both the experiment (abstract) and the datasets (instances) e.g. in the case of the abstraction the instance column would be set to null.  ---------  Samples are often subsituted if the stated samples instances do not produce good results. Scientists ususally have reserve samples or other samples which they want to try out (this usually happens 50% of the time as an estimate on ISIS) this can happen due to a variety of reasons:  1) the sample instances not producing good results 2) the experiment going better than expected and having time left to look at a reserve sample  This is not usually a problem if the sample safety characteristics are the same - usually the will just substitute the sample however if they are  1) have very different sample safety  2) are a totally different sample and they person is attempting to queue jump by analysing a particularly ''hot'' (from a research perspective) compound   then a station scientist must be asked/invovled  1) as can happen - sample can can explode and the people going in to clear up need to know if these are for example radioactive 2) this is queue jumping and can be attempted often but is considered to be unfair play and is actively stopped'
;

COMMENT ON TABLE SHIFT IS 'need by applications where icat will be on the beam line such that a match between who is logged in and what experiment they are performing can be accurately acertained - more operational than archive feature.'
;

COMMENT ON TABLE STUDY IS 'Study now used to aggregate investigations'
;

COMMENT ON TABLE THIS_ICAT IS 'information about the facility served by this instance of icat'
;

COMMENT ON TABLE USER_ROLES IS 'This table records special roles, eg Administrators, assigned to the users of the applications which access the database.  These users will not necessarily also be facility users.'
;

COMMENT ON COLUMN APPLICATIONS.FACILITY_ACQUIRED IS 'added for consistency'
;

COMMENT ON COLUMN APPLICATIONS.DELETED IS 'added for consistency'
;

COMMENT ON COLUMN DATAFILE.DATAFILE_VERSION IS 'e.g. a param divided by 4 and every calculation in the file was wrong so you correct this and then generate a new version of the file.  These types of errors could happen in the beginning - give people the chance to update the datafile metadata but this would necessitate the datafile.  Another case could be where the datafile points to the wrong sample (derived from the dataset) - this will require re-versioning such that people can compare there versions with that in the database.  This should be rare but could happen due to the above reasons. '
;

COMMENT ON COLUMN DATAFILE.DATAFILE_VERSION_COMMENT IS 'why there was a new version of the comment and what has changed - can inform the user to see if they really wanto update their files - i.e. was the change relevent for them.'
;

COMMENT ON COLUMN DATAFILE.LOCATION IS 'The location of the file - this could be an SRB URI/L for example. This should be the full qualified path and not relative.'
;

COMMENT ON COLUMN DATAFILE.DATAFILE_FORMAT IS 'format of the file e.g. NeXus e.g. the MIME type'
;

COMMENT ON COLUMN DATAFILE.DATAFILE_CREATE_TIME IS 'can search for all the files which were modified after they were created if you do not have a reference date. Note for new version this would create a new record in the datafile table the link from investigation would be cut but a link in related_datafiles should show you the progeny.'
;

COMMENT ON COLUMN DATAFILE.DATAFILE_MODIFY_TIME IS 'can search for the files that are last modified since you have downloaded a set.'
;

COMMENT ON COLUMN DATAFILE.FILE_SIZE IS 'this is the size in bytes (not on disk) but actual size. this column should be a parameter but it is needed often and checking with some systems for file sizes can take a lot of time'
;

COMMENT ON COLUMN DATAFILE.COMMAND IS 'stores the command line used to create this files.  It is here and not in related datafiles as there are instances where you would not reference to the source file locally.  As capturing the command is able to be made automatic but determining the source file is more difficult as one cannot necessarily automatically determine its provenance.'
;

COMMENT ON COLUMN DATAFILE.CHECKSUM IS 'for fixity'
;

COMMENT ON COLUMN DATAFILE.SIGNATURE IS 'for fixity'
;

COMMENT ON COLUMN DATAFILE_PARAMETER.DESCRIPTION IS 'from where and how the parameter was recorded or extracted as oppose to a definition of the parameter, the latter being defined in the parameter table'
;

COMMENT ON COLUMN DATASET.SAMPLE_ID IS 'this can be null as calibration datasets will not have a sample'
;

COMMENT ON COLUMN DATASET.NAME IS 'the basis of this should be e.g. the run_number for isis'
;

COMMENT ON COLUMN DATASET.DATASET_TYPE IS 'if Investigation.inv_type == EXPERIMENT or Investigation.inv_type == CALIBRATION  then dataset_type could be any of the following: 1.    PRE_EXPERIMENT_DATA 2.    DETECTOR_CALIBRATION (one detector) 3.    EXPERIMENT_CALIBRATION (with a calibration sample) 4.    EXPERIMENT_RAW 5.    LASER_SHOT (CLF specific) 6.    LASER_DIAGNOSTICS (CLF specific) 7.    TARGERT_DATA 8.    SIMULATION 9.    ANALYSIS '
;

COMMENT ON COLUMN DATASET.DATASET_STATUS IS 'empty ongoing (e.g. clf waiting for the glass plate to be analysed) complete'
;

COMMENT ON COLUMN DATASET.LOCATION IS 'This is the location or root designation of the dataset this is useful for specifying all the files in a directory or for giving a physical root designation to nested files locations specified in the flat datafile table to allow applications to display and download the nested structures.'
;

COMMENT ON COLUMN DATASET.DESCRIPTION IS 'most of the time this will be empty.  ------------  However a description of the RAW data should/could be filled by GDA e.g. important parameters (e.g. temp might change a few degrees but the angle of the sample might be very important so that this is a place to highlight such facts) e.g. this could be used to describe how the data was ''cut''. E.g. in CLF they cut by shot - i.e. one dataset per shot.  -----------  also when dataset_type is pre_experiment_data this could be really important to describe why certain files have been added and what their purpost is.'
;

COMMENT ON COLUMN DATASET_PARAMETER.UNITS IS 'SI name of the units need reference to a lookup table UNIT.  Use N/A when no Unit applies.'
;

COMMENT ON COLUMN DATASET_PARAMETER.RANGE_TOP IS 'work being done to see if these are necessary'
;

COMMENT ON COLUMN DATASET_PARAMETER.RANGE_BOTTOM IS 'work being done to see if these are necessary'
;

COMMENT ON COLUMN DATASET_PARAMETER.ERROR IS 'work being done to see if these are necessary'
;

COMMENT ON COLUMN DATASET_PARAMETER.DESCRIPTION IS 'from where and how the parameter was recorded or extracted as oppose to a definition of the parameter, the latter being defined in the parameter table'
;

COMMENT ON COLUMN FACILITY_CYCLE.DESCRIPTION IS 'should the facility go here or should we have another column'
;

COMMENT ON COLUMN FACILITY_USER.FACILITY_USER_ID IS 'facility_user_id should be self consistent across the database and usually refers to a user numbering system which is valid inside a particular facility in the case of ISIS and DLS this is a number based system but it need not be.'
;

COMMENT ON COLUMN FACILITY_USER.FEDERAL_ID IS 'federal_id should be self consistent across the database and usually refers to a user numbering system which is valid across an (virtual or real) organisation e.g. fed-id at CCLRC or DN schemes. Thus it is generalised as a string as this can accomodate a numbering system also.'
;

COMMENT ON COLUMN FACILITY_USER.TITLE IS 'taken from user database or cdr'
;

COMMENT ON COLUMN FACILITY_USER.INITIALS IS 'from user db or cdr'
;

COMMENT ON COLUMN FACILITY_USER.FIRST_NAME IS 'from user db or cdr'
;

COMMENT ON COLUMN FACILITY_USER.MIDDLE_NAME IS 'from user db or cdr'
;

COMMENT ON COLUMN FACILITY_USER.LAST_NAME IS 'from user db or cdr'
;

COMMENT ON COLUMN ICAT_AUTHORISATION.ID IS 'allow ORM systems (e.g. EJB3) layers to work effectively they don''t work well with unique keys only primary keys'
;

COMMENT ON COLUMN ICAT_AUTHORISATION.USER_ID IS 'this should be the user identifier - e.g. federal id or ''ANY'' for public or an application designation'
;

COMMENT ON COLUMN ICAT_AUTHORISATION.ROLE IS 'ROLE from the icat_role table'
;

COMMENT ON COLUMN ICAT_AUTHORISATION.USER_CHILD_RECORD IS 'if there any this_table.id fields for which this record is a parent - there will be one as this is based on the user'
;

COMMENT ON COLUMN ICAT_AUTHORISATION.ELEMENT_TYPE IS 'can be investigation, dataset or datafile'
;

COMMENT ON COLUMN ICAT_AUTHORISATION.ELEMENT_ID IS 'if null then this has special meaning please see the authorisation specification for icat3'
;

COMMENT ON COLUMN ICAT_AUTHORISATION.PARENT_ELEMENT_TYPE IS 'needed if element_type is a dataset or datafile to give context'
;

COMMENT ON COLUMN ICAT_ROLE.ROLE_WEIGHT IS 'derived from the weight given for the actions a role can perform meant to allow an easy way of working out which roles are of equal or lower authority'
;

COMMENT ON COLUMN INSTRUMENT.SHORT_NAME IS 'Needed as often (e.g. ISIS)  instrument short names cannot be generated automatically from long names e.g. CRISP (CSP), HRPD (HRP), PRISMA (PRS).'
;

COMMENT ON COLUMN INVESTIGATION.INV_NUMBER IS 'this is the experiment number e.g. the rb number from isis. In the case ISIS this is usually the proposal number but proposals can be split into separate experiments each with their own number - in which case it actuall maps to the approved proposal number'
;

COMMENT ON COLUMN INVESTIGATION.VISIT_ID IS 'Sometimes (e.g. in the case of DLS) investigation are consortium based i.e. carried out by a range of people from different institutions who manage their own time slot on the instrument. So in effect the investigation is multi-faceted where different groups should not have access to the data from other groups. In the case of ISIS and CLF this can be set to null or a constant value'
;

COMMENT ON COLUMN INVESTIGATION.FACILITY_CYCLE IS 'facilities cycle - where this is defined as the time between two maintenance periods of the light/neutron/laser sources. this is usually a name - e.g. year & number'
;

COMMENT ON COLUMN INVESTIGATION.INSTRUMENT IS 'multimple instruments per approved proposal will now be different investigations with different instrument inside icat - this was requested by noth DLS and ISIS - rather than attach instrument at the dataset level. This is due in part to common searches being in terms of instrument and experiment number as oppose to title and drilling down..'
;

COMMENT ON COLUMN INVESTIGATION.TITLE IS 'the proposal is usually the source of the investigation.title however this could be modified by the user to reflect more accurately the real experiment being performed as oppose to the one specified in the proposal'
;

COMMENT ON COLUMN INVESTIGATION.INV_TYPE IS 'should match the investigation_type.name values - e.g. experiment or calibration  as calibrations can be adhoc not just at the beginning of a cycle but also when an instrument if fixed then these are  modelled as separate investigations. The linkage to these by experimental investigations is done via the range of time_stamps on the collected datafiles in that particular experiment.'
;

COMMENT ON COLUMN INVESTIGATION.INV_ABSTRACT IS 'description of the experiment e.g. based on the proposal'
;

COMMENT ON COLUMN INVESTIGATION.PREV_INV_NUMBER IS 'experiment number of a preceding and related experiment. e.g. in a chain of such experiments.'
;

COMMENT ON COLUMN INVESTIGATION.GRANT_ID IS 'funding grant identification this is taken from the proposal system. in addition the person and their role in the funding institution need to be know to identify completely where the money for this investigation has come from e.g. EPSRC and the person who signed it off'
;

COMMENT ON COLUMN INVESTIGATION.INV_PARAM_NAME IS 'defining parameter name for investigation based on the facility e.g. in the case of ISIS this maybe run number range for the experiment. this may later be removed and replaces with a investigation_parameter table in versions of icat after 3.3'
;

COMMENT ON COLUMN INVESTIGATION.INV_PARAM_VALUE IS 'the facility specific value of rhe inv_param_name e.g. the actual range of numbers in some specified format for the range of values designating the run numbers'
;

COMMENT ON COLUMN INVESTIGATION.INV_START_DATE IS 'The official start date-time of the experiment e.g. in isis as of the time of writing this could be derived from the date-time that the first raw datafile was read from the instrument.'
;

COMMENT ON COLUMN INVESTIGATION.INV_END_DATE IS 'The official end date-time of the experiment e.g. in isis as of the time of writing this could be derived from the date-time that the latest raw datafile was read from the instrument.'
;

COMMENT ON COLUMN INVESTIGATION.RELEASE_DATE IS 'This is the date in the future that the raw data will be made available to other users (or publically available) - this is informed by the data policy of the facility (e.g. 1 year or 2 years).'
;

COMMENT ON COLUMN INVESTIGATION.CREATE_ID IS 'Stores the id if the user who created the record.  If the record was created by the propagation process this will be set to something like ''FROM PROPAGATION''.  If a record was created in an ICAT application and an equivalent record was created in Duodesk then the propagation process will update this field to ''FROM PROPAGATION''.'
;

COMMENT ON COLUMN INVESTIGATION.DELETED IS 'Shows whether the record is viewable or not.'
;

COMMENT ON COLUMN INVESTIGATION.SRC_HASH IS 'This stores a hash key to identify the records in a business system (e.g Duodesk) which are the source of approved proposals in ICAT ( the business system (e.g. Duodesk) primary key values are hashed together, this is needed as one icat record is often sourced from multiple records in the business system.'
;

COMMENT ON COLUMN INVESTIGATION_TYPE.SEQ_NUMBER IS 'Many times, you want to display options in a particular order of relevance (which is not likely to be alphabetical).  If you have a ‘seq_number’ column then you can add new options and adjust their order without code changes or having to reorder rows in the database'
;

COMMENT ON COLUMN INVESTIGATOR.FACILITY_USER_ID IS 'facility_user_id should be self consistent across the database and usually refers to a user numbering system which is valid inside a particular facility in the case of ISIS and DLS this is a number based system but it need not be.'
;

COMMENT ON COLUMN INVESTIGATOR.ROLE IS 'For example:  Principal Investigator, Collaborator'
;

COMMENT ON COLUMN PARAMETER.UNITS IS 'the unit for this parameter. note any given parameters can be at multiple units this is needed for added flexibility from different data sources e.g. user office systems and values collected at proposal time.  Use N/A when no Unit applies.'
;

COMMENT ON COLUMN PARAMETER.UNITS_LONG_VERSION IS 'long verson of units - unit_abreviation used in practice.'
;

COMMENT ON COLUMN PARAMETER.SEARCHABLE IS 'Y or y - for allowing searches using this parameter and anything else for N including null'
;

COMMENT ON COLUMN PARAMETER.NUMERIC_VALUE IS 'Y or y denote that the value of the parameter is a number - anything else denotes that it is a string'
;

COMMENT ON COLUMN PARAMETER.NON_NUMERIC_VALUE_FORMAT IS 'where the value is a string this allows that value to be documented according to the rules or a regular expression.'
;

COMMENT ON COLUMN PARAMETER.IS_SAMPLE_PARAMETER IS 'Y or y denote that the parameter is relevent for association with samples'
;

COMMENT ON COLUMN PARAMETER.IS_DATASET_PARAMETER IS 'Y or y denote that the parameter is relevent for association with datasets'
;

COMMENT ON COLUMN PARAMETER.IS_DATAFILE_PARAMETER IS 'Y or y denote that the parameter is relevent for association with datafiles'
;

COMMENT ON COLUMN PARAMETER.DESCRIPTION IS 'this describes the parameter'
;

COMMENT ON COLUMN PARAMETER.VERIFIED IS 'if Y this means that the parameter was loaded from the facility spreadsheet or list of approved values or that the parameter was unverified but has been checked and is now verified. N means that the parameter is not verified i.e. it has not been approved by the facility'
;

COMMENT ON COLUMN PUBLICATION.REPOSITORY_ID IS 'this does no necessarily have to be a number'
;

COMMENT ON COLUMN PUBLICATION.REPOSITORY IS 'The name of the repository e.g. CCLRC ePubs'
;

COMMENT ON COLUMN RELATED_DATAFILES.RELATION IS 'e.g. the nature of the relation ship - i.e. <dest_file> a <relation> of <source_file>  where relation could be for example : subset newer version reduced used the configuration of - e.g. sample enviroment (configuration, temperature,pressure)   '
;

COMMENT ON COLUMN SAMPLE.NAME IS 'descriptive name of the sample'
;

COMMENT ON COLUMN SAMPLE.INSTANCE IS 'this is the instance of the sample e.g. 1,2,3 etc.  this will be null in the case where the abstract sample is being described'
;

COMMENT ON COLUMN SAMPLE.CHEMICAL_FORMULA IS 'this is the chemical formula of the sample. note this can be null in cases when there is a complex layered target or where the chemical formula is unknown or only partially known. or when trying to study the interface between two solids - in these cases more support maybe needed if deemded necessary.'
;

COMMENT ON COLUMN SAMPLE.SAFETY_INFORMATION IS 'This field holds sample safety / sample hazard information'
;

COMMENT ON COLUMN SAMPLE.PROPOSAL_SAMPLE_ID IS 'A copy of the sample_id from the database from which this record was imported.  This lets us propoagate changes made to a sample''s child tables, such as  sample_parameter, from the original database to this one.'
;

COMMENT ON COLUMN SAMPLE_PARAMETER.DESCRIPTION IS 'from where and how the parameter was recorded or extracted as oppose to a definition of the parameter, the latter being defined in the parameter table'
;

COMMENT ON COLUMN STUDY.ID IS 'primary key field'
;

COMMENT ON COLUMN STUDY.NAME IS 'This should be unique in the table'
;

COMMENT ON COLUMN STUDY.PURPOSE IS 'the reason for aggregating this particular set of investigations i.e. the aggregation criteria used'
;

COMMENT ON COLUMN STUDY.STATUS IS 'this could be ongoing or complete as there are additional investigations planned in the future which will be applicable to this study'
;

COMMENT ON COLUMN STUDY.RELATED_MATERIAL IS 'e.g. related studies in different facility databases - same or similar sample investigated at a different facility (e.g. DLS or CLF if work done at ISIS). To allow the connection of different sources of relevent information - at the moment this is freetext but this may become more structured in the future'
;

COMMENT ON COLUMN STUDY.STUDY_CREATION_DATE IS 'date the study was created'
;

COMMENT ON COLUMN STUDY.STUDY_MANAGER IS 'This should map to the USER.ID table.column, as the user who creates the study need not be an investigator but should be known to be a registered user of the facility.  This also acts as the authorisation to modify the study and links to associated investigations.'
;

COMMENT ON COLUMN STUDY.MOD_TIME IS 'time record modified'
;

COMMENT ON COLUMN STUDY.MOD_ID IS 'user.id of last modifying user'
;

COMMENT ON COLUMN STUDY_STATUS.DESCRIPTION IS 'a description of what the study status actually means'
;

COMMENT ON COLUMN THIS_ICAT.DAYS_UNTIL_PUBLIC_RELEASE IS 'The number of days until the raw data is made publically available for a given experiment - calculated from the investigation.create_time. a value of 0 means that the data should be made immediately available'
;

COMMENT ON COLUMN USER_ROLES.USERNAME IS 'The user''s single-sign-on username.  Must be upper case.'
;

COMMENT ON COLUMN USER_ROLES.FACILITY_ACQUIRED IS 'added to this table for consistency'
;

COMMENT ON COLUMN USER_ROLES.DELETED IS 'added for consistency'
;

CREATE SEQUENCE datafile_id_seq START WITH 100 NOCACHE;
CREATE SEQUENCE dataset_id_seq START WITH 100 NOCACHE;
CREATE SEQUENCE investigation_id_seq START WITH 100 NOCACHE;
CREATE SEQUENCE publication_id_seq START WITH 100 NOCACHE;
CREATE SEQUENCE sample_id_seq START WITH 100 NOCACHE;
CREATE SEQUENCE software_version_id_seq START WITH 100 NOCACHE;
CREATE SEQUENCE study_id_seq START WITH 100 NOCACHE;
CREATE SEQUENCE topic_id_seq START WITH 100 NOCACHE;
CREATE SEQUENCE ICAT_AUTHORISATION_ID_SEQ START WITH 300 NOCACHE;

