CREATE TABLE CLEANUP_SAMPLE_PARAMETER
(
  SAMPLE_ID          NUMBER(38)                 NOT NULL,
  NAME               VARCHAR2(255 BYTE)         NOT NULL,
  UNITS              VARCHAR2(255 BYTE)         NOT NULL,
  STRING_VALUE       VARCHAR2(4000 BYTE),
  NUMERIC_VALUE      FLOAT(126),
  ERROR              VARCHAR2(255 BYTE),
  RANGE_TOP          VARCHAR2(255 BYTE),
  RANGE_BOTTOM       VARCHAR2(255 BYTE),
  DESCRIPTION        VARCHAR2(4000 BYTE),
  MOD_TIME           TIMESTAMP(1)               NOT NULL,
  MOD_ID             VARCHAR2(255 BYTE)         NOT NULL,
  CREATE_TIME        TIMESTAMP(1)               NOT NULL,
  CREATE_ID          VARCHAR2(255 BYTE)         NOT NULL,
  FACILITY_ACQUIRED  VARCHAR2(1 BYTE)           NOT NULL,
  DELETED            VARCHAR2(1 BYTE)           NOT NULL
);
