CREATE TABLE ICATDLS33.STORAGED_INGEST_ERROR
(
  ID           NUMBER,
  LOG_DATE     DATE,
  VISIT_ID     VARCHAR2(100 BYTE),
  ERROR_NOTES  VARCHAR2(1000 BYTE)
);


GRANT SELECT ON ICATDLS33.STORAGED_INGEST_ERROR TO DLS_STATS;


CREATE TABLE ICATDLS33.STORAGED_INGEST_LOG
(
  ID         NUMBER,
  LOG_DATE   DATE,
  VISIT_ID   VARCHAR2(100 BYTE),
  DATASETS   NUMBER,
  DATAFILES  NUMBER,
  NOTES      VARCHAR2(1000 BYTE)
);

GRANT SELECT ON ICATDLS33.STORAGED_INGEST_LOG TO DLS_STATS;

CREATE TABLE ICATDLS33.STORAGED_VISIT
(
  BEAMLINE     VARCHAR2(100 BYTE),
  YEAR         NUMBER,
  VISIT_ID     VARCHAR2(100 BYTE),
  TOTAL_FILES  NUMBER,
  VISIT_SIZE   NUMBER
);

GRANT SELECT ON ICATDLS33.STORAGED_VISIT TO DLS_STATS;

