CREATE TABLE INV_INCLUDE 
(
  ID NUMBER(38, 0) NOT NULL 
, NAME VARCHAR2(255 BYTE) 
, CONSTRAINT SYS_C0024492 PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE BETWEEN_COMPARISON 
(
  BETWEEN_ID NUMBER(38, 0) NOT NULL 
, ATTRIBUTE VARCHAR2(255 BYTE) 
, GENERIC_ID NUMBER(38, 0) 
, RH_OBJECT_ID NUMBER(38, 0) 
, LH_OBJECT_ID NUMBER(38, 0) 
, CONSTRAINT SYS_C0024533 PRIMARY KEY 
  (
    BETWEEN_ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE COMP_OPERATOR 
(
  ID NUMBER(38, 0) NOT NULL 
, NAME VARCHAR2(255 BYTE) 
, CONSTRAINT SYS_C0024527 PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE DATAFILE_VIEW 
(
  ID NUMBER(38, 0) NOT NULL 
, DATAFILE_ID NUMBER(38, 0) 
, VIEW_ID NUMBER(38, 0) 
, FILENAME VARCHAR2(255 BYTE) 
, FILESIZE NUMBER 
, FORMAT VARCHAR2(255 BYTE) 
, AGE VARCHAR2(255 BYTE) 
, DATASET_ID NUMBER(38, 0) 
, PI_ID NUMBER(38, 0) 
, INVESTIGATION_ID NUMBER(38, 0) 
, INSTRUMENT VARCHAR2(255 BYTE) 
, CONSTRAINT SYS_C0024496 PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE INVESTIGATION_VIEW 
(
  ID NUMBER(38, 0) NOT NULL 
, INVESTIGATION_ID NUMBER(38, 0) 
, VIEW_ID NUMBER(38, 0) 
, PI_ID NUMBER(38, 0) 
, INSTRUMENT VARCHAR2(255 BYTE) 
, START_INDEX NUMBER(*, 0) 
, NO_RESULTS NUMBER(*, 0) 
, INCLUDES NUMBER(38, 0) 
, CONSTRAINT SYS_C0024493 PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE LOGIN 
(
  SESSION_ID VARCHAR2(255 BYTE) NOT NULL 
, USER_ID VARCHAR2(50 BYTE) 
, LOGIN_TIME DATE 
, LOGOUT_TIME DATE 
, CONSTRAINT SYS_C0024485 PRIMARY KEY 
  (
    SESSION_ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SIMPLE_VIEW 
(
  VIEW_ID NUMBER(38, 0) NOT NULL 
, SESSION_ID VARCHAR2(255 BYTE) 
, VIEW_TIME DATE 
, USER_ID VARCHAR2(50 BYTE) 
, METHOD VARCHAR2(255 BYTE) 
, CONSTRAINT SYS_C0024486 PRIMARY KEY 
  (
    VIEW_ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE DATASET_VIEW 
(
  ID NUMBER(38, 0) NOT NULL 
, DATASET_ID NUMBER(38, 0) 
, VIEW_ID NUMBER(38, 0) 
, PI_ID NUMBER(38, 0) 
, INVESTIGATION_ID NUMBER(38, 0) 
, INSTRUMENT VARCHAR2(255 BYTE) 
, INCLUDES NUMBER(38, 0) 
, CONSTRAINT SYS_C0024489 PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE LOG_INSTRUMENT 
(
  INSTRUMENT_ID NUMBER(38, 0) NOT NULL 
, NAME VARCHAR2(255 BYTE) 
, TYPE VARCHAR2(255 BYTE) 
, CONSTRAINT SYS_C0026305 PRIMARY KEY 
  (
    INSTRUMENT_ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE ADV_INVESTIGATOR 
(
  INVESTIGATOR_ID NUMBER(38, 0) NOT NULL 
, ADV_ID NUMBER(38, 0) NOT NULL 
, CONSTRAINT SYS_C0026302 PRIMARY KEY 
  (
    INVESTIGATOR_ID 
  , ADV_ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE ADVANCED_SEARCH 
(
  ADV_ID NUMBER(38, 0) NOT NULL 
, SEARCH_ID NUMBER(38, 0) 
, TITLE VARCHAR2(255 BYTE) 
, ABSTRACT VARCHAR2(4000 BYTE) 
, SAMPLE VARCHAR2(500 BYTE) 
, INVESTIGATOR VARCHAR2(255 BYTE) 
, DATAFILE VARCHAR2(255 BYTE) 
, RB VARCHAR2(255 BYTE) 
, GRANT_ID NUMBER(38, 0) 
, FACILITY VARCHAR2(255 BYTE) 
, INV_TYPE VARCHAR2(255 BYTE) 
, RUN_START FLOAT(126) 
, RUN_END FLOAT(126) 
, START_DATE DATE 
, END_DATE DATE 
, START_INDEX NUMBER(*, 0) 
, NO_RESULTS NUMBER(*, 0) 
, CASE_SENSITIVE VARCHAR2(10 BYTE) 
, INV_INCLUDE NUMBER(38, 0) 
, VISIT_ID VARCHAR2(255 BYTE) 
, SAMPLE_ID NUMBER(38, 0) 
, CONSTRAINT SYS_C0024504 PRIMARY KEY 
  (
    ADV_ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SEARCH 
(
  SEARCH_ID NUMBER(38, 0) NOT NULL 
, SESSION_ID VARCHAR2(255 BYTE) 
, USER_ID VARCHAR2(50 BYTE) 
, SEARCH_TIME DATE 
, METHOD VARCHAR2(255 BYTE) 
, CONSTRAINT SYS_C0024502 PRIMARY KEY 
  (
    SEARCH_ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE LOG_INVESTIGATOR 
(
  ID NUMBER(38, 0) NOT NULL 
, NAME VARCHAR2(255 BYTE) 
, CONSTRAINT SYS_C0026301 PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE GENERIC 
(
  GENERIC_ID NUMBER(38, 0) NOT NULL 
, CONSTRAINT SYS_C0024515 PRIMARY KEY 
  (
    GENERIC_ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE LOGICAL 
(
  LOGICAL_ID NUMBER(38, 0) NOT NULL 
, TYPE_ID NUMBER(38, 0) 
, RH_WHERE_ID NUMBER(38, 0) 
, LH_WHERE_ID NUMBER(38, 0) 
, CONSTRAINT SYS_C0024519 PRIMARY KEY 
  (
    LOGICAL_ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE TYPE 
(
  ID NUMBER(38, 0) NOT NULL 
, NAME VARCHAR2(255 BYTE) 
, CONSTRAINT SYS_C0024516 PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE COMPARISON 
(
  COMP_ID NUMBER(38, 0) NOT NULL 
, ATTRIBUTE VARCHAR2(255 BYTE) 
, GENERIC_ID NUMBER(38, 0) 
, OPERATOR_ID NUMBER(38, 0) 
, OBJECT_ID NUMBER(38, 0) 
, CONSTRAINT SYS_C0024529 PRIMARY KEY 
  (
    COMP_ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE ADV_KEYWORD 
(
  ADV_ID NUMBER(38, 0) NOT NULL 
, KEYWORD_ID NUMBER(38, 0) NOT NULL 
, CONSTRAINT SYS_C0026310 PRIMARY KEY 
  (
    ADV_ID 
  , KEYWORD_ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE ID_SEQUENCE_TABLE 
(
  NAME VARCHAR2(255 BYTE) NOT NULL 
, VALUE NUMBER(38, 0) 
, CONSTRAINT SYS_C0025099 PRIMARY KEY 
  (
    NAME 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE LOG_KEYWORD 
(
  ID NUMBER(38, 0) NOT NULL 
, KEYWORD VARCHAR2(255 BYTE) 
, CONSTRAINT SYS_C0026309 PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE SIMPLE_WHERE 
(
  WHERE_ID NUMBER(38, 0) NOT NULL 
, GENERIC_ID NUMBER(38, 0) 
, LOGICAL_ID NUMBER(38, 0) 
, CONSTRAINT SYS_C0024517 PRIMARY KEY 
  (
    WHERE_ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE DATASET_INCLUDE 
(
  ID NUMBER(38, 0) NOT NULL 
, NAME VARCHAR2(255 BYTE) 
, CONSTRAINT SYS_C0024488 PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE PARAM_SEARCH 
(
  PARAM_SEARCH_ID NUMBER(38, 0) NOT NULL 
, SEARCH_ID NUMBER(38, 0) 
, METHOD VARCHAR2(255 BYTE) 
, DATASET_INC VARCHAR2(255 BYTE) 
, DATAFILE_INC VARCHAR2(255 BYTE) 
, SAMPLE_INC VARCHAR2(255 BYTE) 
, INVESTIGATION_INC VARCHAR2(255 BYTE) 
, OFFSET NUMBER(*, 0) 
, COUNT NUMBER(*, 0) 
, WHERE_ID NUMBER(38, 0) 
, CONSTRAINT SYS_C0024524 PRIMARY KEY 
  (
    PARAM_SEARCH_ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE DOWNLOAD 
(
  DOWNLOAD_ID NUMBER(38, 0) NOT NULL 
, SESSION_ID VARCHAR2(255 BYTE) 
, USER_ID VARCHAR2(50 BYTE) 
, NO_FILES NUMBER(*, 0) 
, TOTAL_SIZE NUMBER(*, 0) 
, DOWNLOAD_TIME DATE 
, METHOD VARCHAR2(255 BYTE) 
, CONSTRAINT SYS_C0024498 PRIMARY KEY 
  (
    DOWNLOAD_ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE DATAFILE_DOWNLOAD 
(
  ID NUMBER(38, 0) NOT NULL 
, DATAFILE_ID NUMBER(38, 0) 
, DOWNLOAD_ID NUMBER(38, 0) 
, FILENAME VARCHAR2(255 BYTE) 
, FILESIZE NUMBER 
, FORMAT VARCHAR2(255 BYTE) 
, AGE VARCHAR2(255 BYTE) 
, DATASET_ID NUMBER(38, 0) 
, PI_ID NUMBER(38, 0) 
, INVESTIGATION_ID NUMBER(38, 0) 
, INSTRUMENT VARCHAR2(255 BYTE) 
, CONSTRAINT SYS_C0024500 PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE ADV_INSTRUMENT 
(
  INSTRUMENT_ID NUMBER(38, 0) NOT NULL 
, ADV_ID NUMBER(38, 0) NOT NULL 
, CONSTRAINT SYS_C0026306 PRIMARY KEY 
  (
    INSTRUMENT_ID 
  , ADV_ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE COMP_OBJECT 
(
  OBJECT_ID NUMBER(38, 0) NOT NULL 
, STRING_VAL VARCHAR2(255 BYTE) 
, NUM_VAL NUMBER 
, BOOL_VAL VARCHAR2(20 BYTE) 
, CONSTRAINT SYS_C0024528 PRIMARY KEY 
  (
    OBJECT_ID 
  )
  ENABLE 
) 
LOGGING 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE BETWEEN_COMPARISON
ADD CONSTRAINT SYS_C0024534 FOREIGN KEY
(
  GENERIC_ID 
)
REFERENCES GENERIC
(
  GENERIC_ID 
)
ENABLE;

ALTER TABLE BETWEEN_COMPARISON
ADD CONSTRAINT SYS_C0024535 FOREIGN KEY
(
  RH_OBJECT_ID 
)
REFERENCES COMP_OBJECT
(
  OBJECT_ID 
)
ENABLE;

ALTER TABLE BETWEEN_COMPARISON
ADD CONSTRAINT SYS_C0024536 FOREIGN KEY
(
  LH_OBJECT_ID 
)
REFERENCES COMP_OBJECT
(
  OBJECT_ID 
)
ENABLE;

ALTER TABLE DATAFILE_VIEW
ADD CONSTRAINT SYS_C0024497 FOREIGN KEY
(
  VIEW_ID 
)
REFERENCES SIMPLE_VIEW
(
  VIEW_ID 
)
ENABLE;

ALTER TABLE INVESTIGATION_VIEW
ADD CONSTRAINT SYS_C0024494 FOREIGN KEY
(
  VIEW_ID 
)
REFERENCES SIMPLE_VIEW
(
  VIEW_ID 
)
ENABLE;

ALTER TABLE INVESTIGATION_VIEW
ADD CONSTRAINT SYS_C0024495 FOREIGN KEY
(
  INCLUDES 
)
REFERENCES INV_INCLUDE
(
  ID 
)
ENABLE;

ALTER TABLE SIMPLE_VIEW
ADD CONSTRAINT SYS_C0024487 FOREIGN KEY
(
  SESSION_ID 
)
REFERENCES LOGIN
(
  SESSION_ID 
)
ENABLE;

ALTER TABLE DATASET_VIEW
ADD CONSTRAINT SYS_C0024490 FOREIGN KEY
(
  VIEW_ID 
)
REFERENCES SIMPLE_VIEW
(
  VIEW_ID 
)
ENABLE;

ALTER TABLE DATASET_VIEW
ADD CONSTRAINT SYS_C0024491 FOREIGN KEY
(
  INCLUDES 
)
REFERENCES DATASET_INCLUDE
(
  ID 
)
ENABLE;

ALTER TABLE ADV_INVESTIGATOR
ADD CONSTRAINT SYS_C0026303 FOREIGN KEY
(
  INVESTIGATOR_ID 
)
REFERENCES LOG_INVESTIGATOR
(
  ID 
)
ENABLE;

ALTER TABLE ADV_INVESTIGATOR
ADD CONSTRAINT SYS_C0026304 FOREIGN KEY
(
  ADV_ID 
)
REFERENCES ADVANCED_SEARCH
(
  ADV_ID 
)
ENABLE;

ALTER TABLE ADVANCED_SEARCH
ADD CONSTRAINT SYS_C0024505 FOREIGN KEY
(
  SEARCH_ID 
)
REFERENCES SEARCH
(
  SEARCH_ID 
)
ENABLE;

ALTER TABLE ADVANCED_SEARCH
ADD CONSTRAINT SYS_C0024506 FOREIGN KEY
(
  INV_INCLUDE 
)
REFERENCES INV_INCLUDE
(
  ID 
)
ENABLE;

ALTER TABLE SEARCH
ADD CONSTRAINT SYS_C0024503 FOREIGN KEY
(
  SESSION_ID 
)
REFERENCES LOGIN
(
  SESSION_ID 
)
ENABLE;

ALTER TABLE LOGICAL
ADD CONSTRAINT SYS_C0024520 FOREIGN KEY
(
  TYPE_ID 
)
REFERENCES TYPE
(
  ID 
)
ENABLE;

ALTER TABLE LOGICAL
ADD CONSTRAINT SYS_C0024521 FOREIGN KEY
(
  RH_WHERE_ID 
)
REFERENCES SIMPLE_WHERE
(
  WHERE_ID 
)
ENABLE;

ALTER TABLE LOGICAL
ADD CONSTRAINT SYS_C0024522 FOREIGN KEY
(
  LH_WHERE_ID 
)
REFERENCES SIMPLE_WHERE
(
  WHERE_ID 
)
ENABLE;

ALTER TABLE COMPARISON
ADD CONSTRAINT SYS_C0024530 FOREIGN KEY
(
  GENERIC_ID 
)
REFERENCES GENERIC
(
  GENERIC_ID 
)
ENABLE;

ALTER TABLE COMPARISON
ADD CONSTRAINT SYS_C0024531 FOREIGN KEY
(
  OPERATOR_ID 
)
REFERENCES COMP_OPERATOR
(
  ID 
)
ENABLE;

ALTER TABLE COMPARISON
ADD CONSTRAINT SYS_C0024532 FOREIGN KEY
(
  OBJECT_ID 
)
REFERENCES COMP_OBJECT
(
  OBJECT_ID 
)
ENABLE;

ALTER TABLE ADV_KEYWORD
ADD CONSTRAINT SYS_C0026311 FOREIGN KEY
(
  ADV_ID 
)
REFERENCES ADVANCED_SEARCH
(
  ADV_ID 
)
ENABLE;

ALTER TABLE ADV_KEYWORD
ADD CONSTRAINT SYS_C0026312 FOREIGN KEY
(
  KEYWORD_ID 
)
REFERENCES LOG_KEYWORD
(
  ID 
)
ENABLE;

ALTER TABLE SIMPLE_WHERE
ADD CONSTRAINT SYS_C0024518 FOREIGN KEY
(
  GENERIC_ID 
)
REFERENCES GENERIC
(
  GENERIC_ID 
)
ENABLE;

ALTER TABLE SIMPLE_WHERE
ADD CONSTRAINT SYS_C0024523 FOREIGN KEY
(
  LOGICAL_ID 
)
REFERENCES LOGICAL
(
  LOGICAL_ID 
)
ENABLE;

ALTER TABLE PARAM_SEARCH
ADD CONSTRAINT SYS_C0024525 FOREIGN KEY
(
  SEARCH_ID 
)
REFERENCES SEARCH
(
  SEARCH_ID 
)
ENABLE;

ALTER TABLE PARAM_SEARCH
ADD CONSTRAINT SYS_C0024526 FOREIGN KEY
(
  WHERE_ID 
)
REFERENCES SIMPLE_WHERE
(
  WHERE_ID 
)
ENABLE;

ALTER TABLE DOWNLOAD
ADD CONSTRAINT SYS_C0024499 FOREIGN KEY
(
  SESSION_ID 
)
REFERENCES LOGIN
(
  SESSION_ID 
)
ENABLE;

ALTER TABLE DATAFILE_DOWNLOAD
ADD CONSTRAINT SYS_C0024501 FOREIGN KEY
(
  DOWNLOAD_ID 
)
REFERENCES DOWNLOAD
(
  DOWNLOAD_ID 
)
ENABLE;

ALTER TABLE ADV_INSTRUMENT
ADD CONSTRAINT SYS_C0026307 FOREIGN KEY
(
  INSTRUMENT_ID 
)
REFERENCES LOG_INSTRUMENT
(
  INSTRUMENT_ID 
)
ENABLE;

ALTER TABLE ADV_INSTRUMENT
ADD CONSTRAINT SYS_C0026308 FOREIGN KEY
(
  ADV_ID 
)
REFERENCES ADVANCED_SEARCH
(
  ADV_ID 
)
ENABLE;
