#
# This is an example of validating a data file request made via ICAT
#
# In the ISIS implementation files are downloaded by ICAT passing 
# the sessionId and either a datasetId or dataFileIds to an external python
# CGI script on a separate server. For security, this script calls back to
# ICAT to determine the real files to download. If all is OK, a ZIP file 
# is then created and returned
# 
# The ZSI (Zolera Soap Infrastructure) is used to connect to ICAT - two 
# additional files (ICATService_services.py and ICATService_services_types.py) 
# are generated by running wsdl2python on the ICAT.wsdl file and imported here
#
# You will need to modify   ICAT_address   in ICATService_services.py
#
# Author: Freddie Akeroyd, CCLRC ISIS facility, GB
#
import sys
from ICATService_services import *

fp=open('debug.out','w')
service = ICATServiceLocator().getICAT(tracefile=fp)
request = checkDatasetDownloadAccess()
request._sessionId = '08f21079-ab69-491b-8ce5-f0fe876926e2'
request._datasetId = 2
response = service.checkDatasetDownloadAccess(request)
print response._downloadInfo._datafileNames
print response._downloadInfo._userId

request = checkDatafileDownloadAccess()
request._sessionId = '08f21079-ab69-491b-8ce5-f0fe876926e2'
request._datafileIds = [ 2 ]
response = service.checkDatafileDownloadAccess(request)
print response._downloadInfo._datafileNames
print response._downloadInfo._userId
fp.close()
