DROP TRIGGER RECALCULATE_ON_DS_DELETE;
DROP TRIGGER RECALCULATE_ON_DS_UPDATE;
DROP TRIGGER RECALCULATE_ON_DF_DELETE;
DROP TRIGGER RECALCULATE_ON_DF_UPDATE;
DROP TRIGGER RECALCULATE_ON_DF_INSERT;
DROP PROCEDURE UPDATE_INV_FILECOUNT;
DROP PROCEDURE UPDATE_DS_FILECOUNT;
DROP PROCEDURE UPDATE_INV_FILESIZE;
DROP PROCEDURE UPDATE_DS_FILESIZE;
exit