#!/usr/bin/env python
from setup_utils import *
import os
import socket

# icat.server

def uninstall():
    app = actions.getAppName("icat.ear")
    if app: actions.undeploy(app)
    app = actions.getAppName("icat.server")
    if app: actions.undeploy(app)
    actions.unregisterDB("icat")
    actions.deleteJMSResource("jms/ICAT/Topic")
    actions.deleteJMSResource("jms/ICAT/Synch")
    
actions, arg, props = getActions("icat-setup.properties", ["db.vendor", "db.driver", "db.url", "db.username", "db.password"], binDir=True)

binDir = actions.getBinDir();
files = ["testicat", "icatadmin"]
prop_name = "icat.properties"
prop_list = ["lifetimeMinutes", "rootUserNames", "authn.list", "notification.list", "log.list"]

if arg in ["CONFIGURE", "INSTALL"]:
    actions.configure(prop_name, prop_list) 
    icatProperties = getProperties(prop_name, prop_list)
    log4backXml = icatProperties.get("logback.xml")
    if log4backXml:actions.configure(os.path.basename(log4backXml), [], log4backXml)
    actions.checkNoErrors()

if arg == "INSTALL":       
    for v in icatProperties["authn.list"].split():
        if "authn." + v + ".jndi" not in icatProperties:
            abort ("authn.list included " + v + " but authn." + v + ".jndi is not defined") 
    
    for v in icatProperties["notification.list"].split():
        if "notification." + v not in icatProperties:
            abort ("notification.list included " + v + " but notification." + v + " is not defined") 
   
    for v in icatProperties["log.list"].split():
        if "log." + v not in icatProperties:
            abort ("log.list included " + v + " but log." + v + " is not defined")
     
    if  log4backXml:
        dir, file = os.path.split(log4backXml)
        if not os.path.exists(file): abort("log4back.xml file " + file + " not found")
        
    ld = icatProperties.get("lucene.Directory")
    if ld:
        parent = os.path.basename(os.path.normpath(ld))
        if not os.path.exists(parent):
            abort("Parent directory " + parent + " of lucene directory specified in icat.properties does not exist")
            
        if not icatProperties.get("lucene.commitSeconds"):
            abort("'lucene.commitSeconds' not specified in icat.properties")
        
    actions.installFile("icat.properties")
    if log4backXml:
        dir, file = os.path.split(log4backXml)
        if dir:
            actions.installFile(file, dir)
        else:
            actions.installFile(file)
    
    try:           
        uninstall()
        actions.registerDB("icat", props["db.vendor"], props["db.driver"], props["db.url"], props["db.username"], props["db.password"])
        actions.createJMSResource("javax.jms.Topic", "jms/ICAT/Topic")
        actions.createJMSResource("javax.jms.Topic", "jms/ICAT/Synch")
        
        actions.convertWarfile(jmsTopicConnectionFactory=icatProperties.get("jms.topicConnectionFactory")
                               )    
        jmsHostPort = props.get("jmsHostPort")
        if jmsHostPort:
            bits = jmsHostPort.split(":")
            if len(bits) != 2: abort("jmsHostPort must contain a colon separator")
            jmsHost = bits[0].strip()
            jmsPort = bits[1].strip()
            if socket.getfqdn() == socket.getfqdn(jmsHost): 
                jmsHostPort = None
            else:
                jmsHostPort = jmsHost + ":" + jmsPort
        if jmsHostPort:
            actions.asadmin("set resources.connector-connection-pool.jms/ICAT/CentralConnectionFactory-Connection-Pool.property.AddressList=" + jmsHostPort)
            actions.asadmin("set resources.connector-connection-pool.jms/ICAT/TopicConnectionFactory-Connection-Pool.property.AddressList=" + jmsHostPort)
            
        actions.deploy(deploymentorder=100)
        
        if not os.path.isdir(binDir): abort ("Please create directory " + binDir + " and try again.")
        for file in files:   
            if platform.system() != "Windows": os.chmod(file, 0755)    
            actions.installFile(file , binDir)
    except Exception, e:
        abort(str(e))
                
if arg == "UNINSTALL":
    icatProperties = actions.getProperties(prop_name, prop_list)
    log4backXml = icatProperties.get("logback.xml")
    
    actions.removeFile(prop_name)
    if log4backXml:
        dir, file = os.path.split(log4backXml)
        if dir:
            actions.removeFile(file, dir)
        else:
            actions.removeFile(file)
    
    try:
        uninstall()
        for file in files:
            actions.removeFile(file, binDir) 
    except Exception, e:
        abort(str(e))       
    
            
    
