#!/usr/bin/env python

from suds.client import Client

import logging
import sys
import getpass

logging.basicConfig(level=logging.CRITICAL)

args = sys.argv
if len(args) < 3 or len(args) % 2 != 1:
    print >> sys.stderr, "\nThis must have two fixed arguments: url and plugin mnemonic\nfollowed by pairs of arguments to represent the credentials. For example\n\n    ", args[0], "https://example.com:8181 db username root password guess\n"
    sys.exit(1)

url = args[1]
plugin = args[2]

suffix = "/ICATService/ICAT?wsdl"
if not url.endswith(suffix): url = url + suffix
client = Client(url)
service = client.service
factory = client.factory

credentials = factory.create("credentials")
for i in range (3, len(args), 2):
    entry = factory.create("credentials.entry")
    entry.key = args[i]   
    if args[i + 1] == "-":
        entry.value = getpass.getpass()
    else:
        entry.value = args[i + 1]
    credentials.entry.append(entry)
    
print "ICAT version", service.getApiVersion() 

sessionId = service.login(plugin, credentials)
print "Logged in as", service.getUserName(sessionId), "with", service.getRemainingMinutes(sessionId), "minutes to go"

groups = service.search(sessionId, "Grouping[name='annoying animals']")
if len(groups): 
    print "Grouping 'annoying animals' already exist - they will be deleted"
    for group in groups:
        service.delete(sessionId, group)
        
group = factory.create("grouping")
group.name = "annoying animals"
service.create(sessionId, group)

groups = service.search(sessionId, "Grouping[name='annoying animals']")
if len(groups) != 1:
    print >> sys.stderr, "There are now", len(groups), "groupings instead of 1 - something is wrong"
    sys.exit(1)
    
for group in groups:
    service.delete(sessionId, group)
    
groups = service.search(sessionId, "Grouping[name='annoying animals']")
if len(groups):
    print >> sys.stderr, "There are now", len(groups), "groupings instead of 0 - something is wrong"
    sys.exit(1)
    
service.logout(sessionId)
    
print "Login, search, create, delete and logout operations were all successful."
