CREATE TABLE INSTRUMENTDATASET (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CREATE_ID VARCHAR(255) NOT NULL,
	CREATE_TIME DATETIME NOT NULL,
	MOD_ID VARCHAR(255) NOT NULL,
	MOD_TIME DATETIME NOT NULL,
	INSTRUMENT_ID BIGINT NOT NULL,
	DATASET_ID BIGINT NOT NULL,
	PRIMARY KEY (ID)
);

ALTER TABLE INSTRUMENTDATASET ADD CONSTRAINT FK_INSTRUMENTDATASET_INSTRUMENT_ID FOREIGN KEY (INSTRUMENT_ID) REFERENCES INSTRUMENT (ID);
ALTER TABLE INSTRUMENTDATASET ADD CONSTRAINT FK_INSTRUMENTDATASET_DATASET_ID FOREIGN KEY (DATASET_ID) REFERENCES DATASET (ID);
ALTER TABLE INSTRUMENTDATASET ADD CONSTRAINT UNQ_INSTRUMENTDATASET_0 UNIQUE (INSTRUMENT_ID, DATASET_ID);