-- Add table and constraints for InvestigationSamples

CREATE TABLE INVESTIGATIONSAMPLE (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CREATE_ID VARCHAR(255) NOT NULL,
    CREATE_TIME DATETIME NOT NULL,
    MOD_ID VARCHAR(255) NOT NULL,
    MOD_TIME DATETIME NOT NULL,
    INVESTIGATION_ID BIGINT NOT NULL,
    SAMPLE_ID BIGINT NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE INVESTIGATIONSAMPLE ADD CONSTRAINT FK_INVESTIGATIONSAMPLE_INVESTIGATION_ID FOREIGN KEY (INVESTIGATION_ID) REFERENCES INVESTIGATION (ID);
ALTER TABLE INVESTIGATIONSAMPLE ADD CONSTRAINT FK_INVESTIGATIONSAMPLE_SAMPLE_ID FOREIGN KEY (SAMPLE_ID) REFERENCES SAMPLE (ID);
ALTER TABLE INVESTIGATIONSAMPLE ADD CONSTRAINT UNQ_INVESTIGATIONSAMPLE_0 UNIQUE (INVESTIGATION_ID, SAMPLE_ID);

-- Set the PID field of existing Samples

DELIMITER //

CREATE PROCEDURE SET_SAMPLES_PID()
BEGIN
    UPDATE SAMPLE SET PID = CONCAT('_local:', LPAD(ID, 8, '0')), MOD_ID = 'schema_upgrade', MOD_TIME = NOW() WHERE PID IS NULL;
END; //

DELIMITER ;

CALL SET_SAMPLES_PID();

DROP PROCEDURE SET_SAMPLES_PID;

-- Move existing Sample/Investigation relations over to the new table

DELIMITER //

CREATE PROCEDURE MOVE_SAMPLE_INVESTIGATION_RELATIONS()
BEGIN
    DECLARE done BOOLEAN DEFAULT FALSE;
    DECLARE _invid BIGINT;
    DECLARE _id BIGINT;
    DECLARE cur CURSOR FOR SELECT INVESTIGATION_ID, ID FROM SAMPLE;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done := TRUE;

    OPEN cur;
    sampleLoop: LOOP
        FETCH cur INTO _invid, _id;
        IF done THEN
        LEAVE sampleLoop;
        END IF;

        INSERT INTO INVESTIGATIONSAMPLE (CREATE_ID, CREATE_TIME, MOD_ID, MOD_TIME, INVESTIGATION_ID, SAMPLE_ID) VALUES ('schema_upgrade', NOW(), 'schema_upgrade', NOW(), _invid, _id);
    END LOOP sampleLoop;
    CLOSE cur;
END; //

DELIMITER ;

CALL MOVE_SAMPLE_INVESTIGATION_RELATIONS();

DROP PROCEDURE MOVE_SAMPLE_INVESTIGATION_RELATIONS;

-- Alter the Sample table

ALTER TABLE SAMPLE MODIFY PID VARCHAR(255) NOT NULL;
ALTER TABLE SAMPLE DROP CONSTRAINT FK_SAMPLE_INVESTIGATION_ID;
ALTER TABLE SAMPLE DROP CONSTRAINT UNQ_SAMPLE_0;
ALTER TABLE SAMPLE ADD CONSTRAINT UNQ_SAMPLE_0 UNIQUE (PID);
ALTER TABLE SAMPLE DROP COLUMN INVESTIGATION_ID;

-- Alter the SampleType table, the constraint on PID needs to be done
-- after populating it

ALTER TABLE SAMPLETYPE DROP CONSTRAINT FK_SAMPLETYPE_FACILITY_ID;
ALTER TABLE SAMPLETYPE DROP CONSTRAINT UNQ_SAMPLETYPE_0;
ALTER TABLE SAMPLETYPE DROP COLUMN FACILITY_ID;
ALTER TABLE SAMPLETYPE MODIFY COLUMN MOLECULARFORMULA VARCHAR(255) DEFAULT NULL;
ALTER TABLE SAMPLETYPE ADD COLUMN PID VARCHAR(255);

-- Populate the PID column for SampleTypes

DELIMITER //

CREATE PROCEDURE SET_SAMPLETYPES_PID()
BEGIN
    UPDATE SAMPLETYPE SET PID = CONCAT('_local:', LPAD(ID, 8, '0')), MOD_ID = 'schema_upgrade', MOD_TIME = NOW();
END; //

DELIMITER ;

CALL SET_SAMPLETYPES_PID();

DROP PROCEDURE SET_SAMPLETYPES_PID;

-- Alter the SampleType table: set the constraint on PID

ALTER TABLE SAMPLETYPE MODIFY COLUMN PID VARCHAR(255) NOT NULL;
ALTER TABLE SAMPLETYPE ADD CONSTRAINT UNQ_SAMPLETYPE_0 UNIQUE (PID);
