-- Alter the SampleType table, the constraint on PID needs to be done
-- after populating it

ALTER TABLE SAMPLETYPE DROP CONSTRAINT FK_SAMPLETYPE_FACILITY_ID;
ALTER TABLE SAMPLETYPE DROP CONSTRAINT UNQ_SAMPLETYPE_0;
ALTER TABLE SAMPLETYPE DROP COLUMN FACILITY_ID;
ALTER TABLE SAMPLETYPE MODIFY (MOLECULARFORMULA NULL);
ALTER TABLE SAMPLETYPE ADD PID VARCHAR2(255);

-- Populate the PID column for SampleTypes

CREATE PROCEDURE SET_SAMPLETYPES_PID AS
BEGIN
    UPDATE SAMPLETYPE SET PID = '_local:' || LPAD(ID, 8, '0'), MOD_ID = 'schema_upgrade', MOD_TIME = CURRENT_TIMESTAMP WHERE PID IS NULL;
END;
/

BEGIN
    SET_SAMPLETYPES_PID;
END;
/

DROP PROCEDURE SET_SAMPLETYPES_PID;

-- Alter the SampleType table: set the constraint on PID

ALTER TABLE SAMPLETYPE MODIFY (PID NOT NULL);
ALTER TABLE SAMPLETYPE ADD CONSTRAINT UNQ_SAMPLETYPE_0 UNIQUE (PID);

exit
