-- Add table and constraints for InvestigationSamples

CREATE TABLE INVESTIGATIONSAMPLE (
    ID NUMBER(19) NOT NULL,
    CREATE_ID VARCHAR2(255) NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    MOD_ID VARCHAR2(255) NOT NULL,
    MOD_TIME TIMESTAMP NOT NULL,
    INVESTIGATION_ID NUMBER(19) NOT NULL,
    SAMPLE_ID NUMBER(19) NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE INVESTIGATIONSAMPLE ADD CONSTRAINT FK_INVESTIGATIONSAMPLE_INVESTIGATION_ID FOREIGN KEY (INVESTIGATION_ID) REFERENCES INVESTIGATION (ID);
ALTER TABLE INVESTIGATIONSAMPLE ADD CONSTRAINT FK_INVESTIGATIONSAMPLE_SAMPLE_ID FOREIGN KEY (SAMPLE_ID) REFERENCES SAMPLE (ID);
ALTER TABLE INVESTIGATIONSAMPLE ADD CONSTRAINT UNQ_INVESTIGATIONSAMPLE_0 UNIQUE (INVESTIGATION_ID, SAMPLE_ID);

-- Set the PID field of existing Samples

CREATE PROCEDURE SET_SAMPLES_PID AS
BEGIN
    UPDATE SAMPLE SET PID = '_local:' || LPAD(ID, 8, '0'), MOD_ID = 'schema_upgrade', MOD_TIME = CURRENT_TIMESTAMP WHERE PID IS NULL;
END;
/

BEGIN
    SET_SAMPLES_PID;
END;
/

DROP PROCEDURE SET_SAMPLES_PID;

-- Move existing Sample/Investigation relations over to the new table

CREATE PROCEDURE MOVE_SAMPLE_INVESTIGATION_RELATIONS AS
CURSOR CUR IS SELECT INVESTIGATION_ID, ID FROM SAMPLE;
BEGIN
    FOR CUR_SAMPLE in CUR LOOP
        INSERT INTO INVESTIGATIONSAMPLE (CREATE_ID, CREATE_TIME, MOD_ID, MOD_TIME, INVESTIGATION_ID, SAMPLE_ID) VALUES ('schema_upgrade', CURRENT_TIMESTAMP, 'schema_upgrade', CURRENT_TIMESTAMP, CUR_SAMPLE.INVESTIGATION_ID, CUR_SAMPLE.ID);
    END LOOP;
END;
/

BEGIN
    MOVE_SAMPLE_INVESTIGATION_RELATIONS;
END;
/

DROP PROCEDURE MOVE_SAMPLE_INVESTIGATION_RELATIONS;

-- Alter the Sample table

ALTER TABLE SAMPLE MODIFY (PID NOT NULL);
ALTER TABLE SAMPLE DROP CONSTRAINT FK_SAMPLE_INVESTIGATION_ID;
ALTER TABLE SAMPLE DROP CONSTRAINT UNQ_SAMPLE_0;
ALTER TABLE SAMPLE ADD CONSTRAINT UNQ_SAMPLE_0 UNIQUE (PID);
ALTER TABLE SAMPLE DROP COLUMN INVESTIGATION_ID;

-- Alter the SampleType table, the constraint on PID needs to be done
-- after populating it

ALTER TABLE SAMPLETYPE DROP CONSTRAINT FK_SAMPLETYPE_FACILITY_ID;
ALTER TABLE SAMPLETYPE DROP CONSTRAINT UNQ_SAMPLETYPE_0;
ALTER TABLE SAMPLETYPE DROP COLUMN FACILITY_ID;
ALTER TABLE SAMPLETYPE MODIFY (MOLECULARFORMULA NULL);
ALTER TABLE SAMPLETYPE ADD PID VARCHAR2(255);

-- Populate the PID column for SampleTypes

CREATE PROCEDURE SET_SAMPLETYPES_PID AS
BEGIN
    UPDATE SAMPLETYPE SET PID = '_local:' || LPAD(ID, 8, '0'), MOD_ID = 'schema_upgrade', MOD_TIME = CURRENT_TIMESTAMP WHERE PID IS NULL;
END;
/

BEGIN
    SET_SAMPLETYPES_PID;
END;
/

DROP PROCEDURE SET_SAMPLETYPES_PID;

-- Alter the SampleType table: set the constraint on PID

ALTER TABLE SAMPLETYPE MODIFY (PID NOT NULL);
ALTER TABLE SAMPLETYPE ADD CONSTRAINT UNQ_SAMPLETYPE_0 UNIQUE (PID);

exit
