CREATE TABLE INSTRUMENTDATASET (
	ID NUMBER(19) NOT NULL,
	CREATE_ID VARCHAR2(255) NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	MOD_ID VARCHAR2(255) NOT NULL,
	MOD_TIME TIMESTAMP NOT NULL,
	INSTRUMENT_ID NUMBER(19) NOT NULL,
	DATASET_ID NUMBER(19) NOT NULL,
	PRIMARY KEY (ID)
);

ALTER TABLE INSTRUMENTDATASET ADD CONSTRAINT FK_INSTRUMENTDATASET_INSTRUMENT_ID FOREIGN KEY (INSTRUMENT_ID) REFERENCES INSTRUMENT (ID);
ALTER TABLE INSTRUMENTDATASET ADD CONSTRAINT FK_INSTRUMENTDATASET_DATASET_ID FOREIGN KEY (DATASET_ID) REFERENCES DATASET (ID);
ALTER TABLE INSTRUMENTDATASET ADD CONSTRAINT UNQ_INSTRUMENTDATASET_0 UNIQUE (INSTRUMENT_ID, DATASET_ID);

exit