-- Alter the SampleType table, the constraint on PID needs to be done
-- after populating it

ALTER TABLE SAMPLETYPE DROP CONSTRAINT FK_SAMPLETYPE_FACILITY_ID;
ALTER TABLE SAMPLETYPE DROP CONSTRAINT UNQ_SAMPLETYPE_0;
ALTER TABLE SAMPLETYPE DROP COLUMN FACILITY_ID;
ALTER TABLE SAMPLETYPE MODIFY COLUMN MOLECULARFORMULA VARCHAR(255) DEFAULT NULL;
ALTER TABLE SAMPLETYPE ADD COLUMN PID VARCHAR(255);

-- Populate the PID column for SampleTypes

DELIMITER //

CREATE PROCEDURE SET_SAMPLETYPES_PID()
BEGIN
    UPDATE SAMPLETYPE SET PID = CONCAT('_local:', LPAD(ID, 8, '0')), MOD_ID = 'schema_upgrade', MOD_TIME = NOW();
END; //

DELIMITER ;

CALL SET_SAMPLETYPES_PID();

DROP PROCEDURE SET_SAMPLETYPES_PID;

-- Alter the SampleType table: set the constraint on PID

ALTER TABLE SAMPLETYPE MODIFY COLUMN PID VARCHAR(255) NOT NULL;
ALTER TABLE SAMPLETYPE ADD CONSTRAINT UNQ_SAMPLETYPE_0 UNIQUE (PID);
