PROMPT Partition the icat_authorisation table

DROP TABLE ICAT_AUTHORISATION;


CREATE TABLE ICAT_AUTHORISATION
(
  ID                   NUMBER                   NOT NULL,
  USER_ID              VARCHAR2(255 BYTE)       NOT NULL,
  ROLE                 VARCHAR2(255 BYTE)       NOT NULL,
  ELEMENT_TYPE         VARCHAR2(100 BYTE)       NOT NULL,
  ELEMENT_ID           NUMBER,
  PARENT_ELEMENT_TYPE  VARCHAR2(100 BYTE),
  PARENT_ELEMENT_ID    NUMBER,
  MOD_TIME             TIMESTAMP(1)             NOT NULL,
  MOD_ID               VARCHAR2(255 BYTE)       NOT NULL,
  CREATE_TIME          TIMESTAMP(1)             NOT NULL,
  CREATE_ID            VARCHAR2(255 BYTE)       NOT NULL,
  FACILITY_ACQUIRED    VARCHAR2(1 BYTE)         DEFAULT 'Y'                   NOT NULL,
  DELETED              VARCHAR2(1 BYTE)         DEFAULT 'N'                   NOT NULL,
  USER_CHILD_RECORD    NUMBER
)
-- TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
PARTITION BY LIST (ELEMENT_TYPE) 
(  
  PARTITION DATAFILE_PART VALUES ('DATAFILE'),
  PARTITION DATASET_PART VALUES ('DATASET'),
  PARTITION INV_PART VALUES ('INVESTIGATION'),
  PARTITION DEFAULT_PART VALUES (DEFAULT)
);


--indexes


CREATE INDEX ICATISIS_DEV_ID ON ICAT_AUTHORISATION
(USER_ID);

CREATE INDEX ICAT_AUTHORISATION_INDEX1 ON ICAT_AUTHORISATION (ELEMENT_ID);

CREATE INDEX ICAT_AUTHORISATION_INDEX2 ON ICAT_AUTHORISATION (USER_ID, ROLE, ELEMENT_ID);

CREATE INDEX ICAT_AUTHORISATION_INDEX3 ON ICAT_AUTHORISATION (ELEMENT_ID, USER_ID);


CREATE UNIQUE INDEX ICAT_AUTHORISATION_UK1 ON ICAT_AUTHORISATION
(ELEMENT_TYPE, ELEMENT_ID, USER_ID, PARENT_ELEMENT_TYPE, PARENT_ELEMENT_ID) LOCAL;


ALTER TABLE ICAT_AUTHORISATION
ADD CONSTRAINT ICAT_AUTHORISATION_PK PRIMARY KEY
(ID) USING INDEX;


ALTER TABLE ICAT_AUTHORISATION ADD (
  CONSTRAINT ICAT_AUTHORISATION_UK1
 UNIQUE (USER_ID, ELEMENT_TYPE, ELEMENT_ID, PARENT_ELEMENT_TYPE, PARENT_ELEMENT_ID)
 USING INDEX LOCAL);


ALTER TABLE ICAT_AUTHORISATION ADD (
  CONSTRAINT ICAT_AUTHORISATION_ICAT_R_FK1 
 FOREIGN KEY (ROLE) 
 REFERENCES ICAT_ROLE (ROLE));

-- comments - please see script1.sql


